src/Entity/Document.php

[Ticket](https://trello.com/c/AebLuKnQ/3643-5-le-champ-d%C3%A9pos%C3%A9-par-dans-les-informations-dun-document-depuis-un-compte-b%C3%A9n%C3%A9f-est-vide)

 Le champ "Déposé par" dans les informations d'un document, depuis un compte bénéf, est vide

---

assets/controllers/tooltip_controller.js
assets/css/appV2/theme.scss
src/Entity/MembreCentre.php
src/ManagerV2/RelayManager.php
templates/v2/base.html.twig
templates/v2/common/_card.html.twig
templates/v2/pro/list/_update_permission_button.html.twig
tests/v2/Controller/UserController/ToggleUserInvitationTest.php
tests/v2/Entity/UserTest.php

[Ticket](https://trello.com/c/HhUAgxBs/3828-2-quand-on-affilie-un-membre-%C3%A0-un-centre-il-est-par-d%C3%A9faut-en-gestion-des-b%C3%A9n%C3%A9ficiaires-en-droit)
++ Traitements des retours: [Ticket](https://trello.com/c/04EDvA8U/3784-8-pro-lister-professionnels-sur-la-card-dun-professionnels-jai-un-composant-pour-modifier-ses-droits)

Quand on affilie un membre à un centre il est par défaut en “Gestion des bénéficiaires” en droit

---

assets/controllers/tooltip_controller.js
assets/css/appV2/theme.scss
src/Entity/MembreCentre.php
src/ManagerV2/RelayManager.php
templates/v2/base.html.twig
templates/v2/common/_card.html.twig
templates/v2/pro/list/_update_permission_button.html.twig
tests/v2/Controller/UserController/ToggleUserInvitationTest.php
tests/v2/Entity/UserTest.php

[Ticket](https://trello.com/c/HhUAgxBs/3828-2-quand-on-affilie-un-membre-%C3%A0-un-centre-il-est-par-d%C3%A9faut-en-gestion-des-b%C3%A9n%C3%A9ficiaires-en-droit)
++ Traitements des retours: [Ticket](https://trello.com/c/04EDvA8U/3784-8-pro-lister-professionnels-sur-la-card-dun-professionnels-jai-un-composant-pour-modifier-ses-droits)

[Main] Quand on affilie un membre à un centre il est par défaut en “Gestion des bénéficiaires” en droit

---

src/ControllerV2/BeneficiaryAffiliationController.php
tests/v2/Controller/BeneficiaryAffiliationController/SendSmsAffiliationCodeTest.php
tests/v2/Validator/SecretAnswerConstraintTest.php

[Ticket](https://trello.com/c/03Y3vfIO/3864-3-affilier-benef-existant-si-le-b%C3%A9n%C3%A9f-a-indiqu%C3%A9-un-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-il-peut-valider-laffiliation-par-sms-tests)

(3) [Affilier benef existant] Si le bénéf a indiqué un numéro de téléphone, il peut valider l'affiliation par SMS (tests)

---

src/Entity/Traits/DeactivatableTrait.php
src/ManagerV2/RelayManager.php
tests/v2/Manager/RelayManager/RemoveUserFromRelayTest.php

[Ticket](https://trello.com/c/VOdJ6884/4029-3-v2-si-je-retire-un-professionnel-dun-relais-alors-quil-est-affili%C3%A9-%C3%A0-un-unique-relais-son-compte-membre-est-d%C3%A9sactiv%C3%A9)

(3) V2 - Si je retire un professionnel d'un relais alors qu'il est affilié à un unique relais, son compte membre est désactivé

---

config/doctrine/SharedDocument.orm.yml
src/Entity/Beneficiaire.php
src/EventSubscriber/VaultSizeEventSubscriber.php

[(3) [Enquête 3h] La capacité de stockage indiquée ne correspond pas au poids des docs stockés](https://trello.com/c/dmOAEUI1/4253-3-ajout-dun-pop-up-si-aucun-centre-s%C3%A9lectionn%C3%A9-%C3%A0-laffiliation-dun-b%C3%A9n%C3%A9ficiaire-qui-a-d%C3%A9j%C3%A0-un-cfn)

[Main] Feature/restore feature sum available space

---

templates/v2/user_creation/components/_permissions_checkboxes.html.twig
templates/v2/user_creation/components/_relays_checkbox.html.twig

[Ticket](https://trello.com/c/FAMAPzEj/4315-1-sur-la-cr%C3%A9ation-dun-b%C3%A9n%C3%A9ficiaire-%C3%A7a-a-pas-de-sens-de-mettre-le-tooltip-le-b%C3%A9n%C3%A9ficiaire-est-d%C3%A9j%C3%A0-affili%C3%A9-%C3%A0-ce-centre-%C3%A9tant-donn)
[Ticket](https://trello.com/c/zQkYn7Oz/4302-05-modifier-gestion-professionnels-en-gestion-d%C3%A9quipe)

Modifier "Gestion professionnels" en "Gestion d'équipe" + Sur la création d'un bénéficiaire pas de tooltip sur les checkboxes d'affiliation

---

templates/v2/user_creation/components/_permissions_checkboxes.html.twig
templates/v2/user_creation/components/_relays_checkbox.html.twig

[Ticket](https://trello.com/c/FAMAPzEj/4315-1-sur-la-cr%C3%A9ation-dun-b%C3%A9n%C3%A9ficiaire-%C3%A7a-a-pas-de-sens-de-mettre-le-tooltip-le-b%C3%A9n%C3%A9ficiaire-est-d%C3%A9j%C3%A0-affili%C3%A9-%C3%A0-ce-centre-%C3%A9tant-donn)
[Ticket](https://trello.com/c/zQkYn7Oz/4302-05-modifier-gestion-professionnels-en-gestion-d%C3%A9quipe)

[Main] Modifier "Gestion professionnels" en "Gestion d'équipe" + Sur la création d'un bénéficiaire pas de tooltip sur les checkboxes d'affiliation

---

src/Form/Type/UserType.php
src/FormV2/ChangePasswordFormType.php
src/FormV2/Field/PasswordField.php
src/FormV2/UserCreation/CreateBeneficiaryType.php
src/FormV2/UserCreation/CreateUserType.php
templates/v2/user_creation/components/_password_card.html.twig

[Ticket](https://trello.com/c/xTV5G92o/4731-2-etqp-%C3%A0-la-cr%C3%A9ation-dun-b%C3%A9n%C3%A9ficiaire-les-chips-de-validation-du-password-doivent-fonctionner)

ETQP à la création d'un bénéficiaire, les chips de validation du password doivent fonctionner

---

src/EventSubscriber/UserCreationSubscriber.php
tests/v2/EventSubscriber/UserCreationSubscriberTest.php

[Ticket](https://trello.com/c/1wNIizZt/4316-3-admin-pourquoi-sur-les-membres-les-cr%C3%A9%C3%A9-par-sont-vides)

Admin : pourquoi sur les membres les "créé par" sont vides ?

---

tests/v2/Manager/EventManager/SendRemindersTest.php

[Ticket](https://trello.com/c/uVbo4N4S/4924-5-enqu%C3%AAte-5h-test-automatis%C3%A9-pour-contr%C3%B4ler-lenvoi-des-rappels-sms)

Test automatisé pour contrôler l'envoi des rappels SMS

---

tests/v2/Manager/EventManager/SendRemindersTest.php

[Ticket](https://trello.com/c/uVbo4N4S/4924-5-enqu%C3%AAte-5h-test-automatis%C3%A9-pour-contr%C3%B4ler-lenvoi-des-rappels-sms)

[2.50.0] Test automatisé pour contrôler l'envoi des rappels SMS

---

assets/controllers/ajax_toggle_controller.js
templates/v2/vault/components/_toggle_visibility_button.html.twig

[Ticket](https://trello.com/c/Qw0jZtpn/4480-3-etqb-sur-le-site-du-cfn-au-niveau-des-documents-je-vois-un-tooltip-passer-partag%C3%A9-ou-passer-priv%C3%A9-comme-sur-lappli)

ETQB, sur le site du CFN au niveau des documents je vois un tooltip "passer partagé" ou "passer privé"

---

assets/controllers/ajax_toggle_controller.js
templates/v2/vault/components/_toggle_visibility_button.html.twig

[Ticket](https://trello.com/c/Qw0jZtpn/4480-3-etqb-sur-le-site-du-cfn-au-niveau-des-documents-je-vois-un-tooltip-passer-partag%C3%A9-ou-passer-priv%C3%A9-comme-sur-lappli)

[2.57.0] ETQB, sur le site du CFN au niveau des documents je vois un tooltip "passer partagé" ou "passer privé" 

---

templates/v2/vault/document/_card.html.twig
templates/v2/vault/folder/_card.html.twig

[Ticket](https://trello.com/c/PTzLrWQy/5162-1-etqp-quand-je-consulte-un-cfn-je-ne-dois-pas-voir-licone-cadenas-priv%C3%A9-sur-les-donn%C3%A9es-persos-partag%C3%A9es)

ETQP quand je consulte un CFN, je ne dois pas voir l'icone cadenas "privé" sur les données persos partagées

---

templates/v2/vault/document/_card.html.twig
templates/v2/vault/folder/_card.html.twig

[Ticket](https://trello.com/c/PTzLrWQy/5162-1-etqp-quand-je-consulte-un-cfn-je-ne-dois-pas-voir-licone-cadenas-priv%C3%A9-sur-les-donn%C3%A9es-persos-partag%C3%A9es)

[2.65.1] ETQP quand je consulte un CFN, je ne dois pas voir l'icone cadenas "privé" sur les données persos partagées

---

assets/controllers/ajax_toggle_controller.js
assets/css/appV2/table.scss
templates/v2/vault/components/_toggle_visibility_button.html.twig
templates/v2/vault/contact/_card.html.twig
templates/v2/vault/document/_card.html.twig
templates/v2/vault/event/_card.html.twig
templates/v2/vault/folder/_card.html.twig
templates/v2/vault/note/_card.html.twig

Added new `leftBar` target to the `ajax_toggle_controller.js` and associated logic to update its color. Modified `_toggle_visibility_button.html.twig` and `_card.html.twig` for better integration and updated styles to visually differentiate shared and not-shared states.
[Ticket](https://trello.com/c/fe8BxvI8/5049-3-etqb-je-vois-un-trait-de-couleur-%C3%A0-gauche-de-litem-correspondant-%C3%A0-l%C3%A9tat-priv%C3%A9-ou-partag%C3%A9-de-mon-dossier-ou-document)

ETQB, je vois un trait de couleur à gauche de l'item correspondant à l'état privé ou partagé de mon dossier ou document

---

src/Entity/Beneficiaire.php
src/ManagerV2/FolderManager.php
tests/v2/Manager/FolderManager/getRootFoldersTest.php

[Ticket](https://trello.com/c/ryBKbp5K/5494-etqp-quand-je-d%C3%A9place-un-dossier-ou-un-document-je-devrais-voir-uniquement-larborescence-des-dossiers-partag%C3%A9s-pour-y-d%C3%A9placer-m)

ETQP, quand je déplace un dossier ou un document, je devrais voir uniquement l'arborescence des dossiers partagés pour y déplacer mon élément

---

src/Entity/Beneficiaire.php
src/Entity/Dossier.php
src/ManagerV2/FolderManager.php
templates/v2/vault/folder/_tree_view_item.html.twig
tests/v2/Manager/FolderManager/getRootFoldersTest.php

**Bug**
- 🐛 [FolderManager] Return shared folders when authenticated as member
> French release notes
**Bug** 
- 🐛 [Dossiers&Documents] Seuls les dossiers partagés sont affichés lors du déplacement d'un document ou d'un dossier

🚀 Release/2.75.0

---

config/packages/monolog.yaml

[Ticket](https://trello.com/c/EPD3HK9k/5581-limiter-les-fichiers-de-deprecations-conserv%C3%A9s-sur-le-serveur)

Limiter les fichiers de deprecations conservés sur le serveur

---

assets/js/home/openstreetmap-marker-generator.js

**Improvement :**
- :recycle: [Home] Reword training with guidance 
**Bug :**
- :bug: [Home/Map] Display centers even if country is not France
**Améliorations :**
- :recycle: [Home] Lien aux supports de formation retirés + changement de wording formation -> accompagnement
**Bugs :**
- :bug: [Home/CarteCentres] Les centres qui ne possèdent pas le pays "France" sont quand même affichés sur la carte

:rocket: 2.81.1
