re-connect/vault

- src/Admin/MembreAdmin.php
[Ticket](https://trello.com/c/XbfkfsCF/3460-22adminbug-daffiliation-lors-de-la-cr%C3%A9ation-dun-membre)
> :bug: [Admin]Bug affiliate member to center during creation

- .github/PULL_REQUEST_TEMPLATE/feature_template.md
- .github/PULL_REQUEST_TEMPLATE/release_template.md
Added two pull request templates : 
- feature
- release
> :memo: [Pull request]Add PR templates

- src/Controller/SecurityController.php
https://trello.com/c/qXqFjvBC/3564-2-impossible-de-se-connecter-au-cfn-quand-on-vient-dune-autre-url
> (2) Impossible de se connecter au CFN quand on vient d'une autre URL

- assets/controllers/loader_controller.js
- assets/css/appV2/components.scss
- assets/css/appV2/general.scss
- src/ControllerV2/BeneficiaryCreationController.php
- src/Entity/Adresse.php
- src/Entity/Attributes/BeneficiaryCreationProcess.php
- src/Entity/Centre.php
- src/FormV2/UserCreation/CreateBeneficiaryType.php
- src/FormV2/UserInformationType.php
- src/ManagerV2/BeneficiaryCreationManager.php
- src/Migrations/Version20230407101235.php
- templates/homeV2/templates/login-form-template.html.twig
- templates/v2/common/_button_with_loader.html.twig
- templates/v2/common/_button_with_loader_content.html.twig
- templates/v2/pro_management_layout.html.twig
- templates/v2/pro_standard_layout.html.twig
- templates/v2/user_affiliation/beneficiary/affiliate_beneficiary_relays.html.twig
- templates/v2/user_affiliation/beneficiary/affiliate_beneficiary_search.html.twig
- templates/v2/user_creation/beneficiary/_abort_button.html.twig
- templates/v2/user_creation/beneficiary/_breadcrumb.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- templates/v2/user_creation/beneficiary/_step_form.html.twig
- templates/v2/user_creation/beneficiary/components/_way_card.html.twig
- templates/v2/user_creation/beneficiary/create_beneficiary.html.twig
- templates/v2/user_creation/beneficiary/create_beneficiary_step.html.twig
- templates/v2/user_creation/components/_generate_password_input.html.twig
https://trello.com/c/FpJLkuCB/3554-5-ux-cr%C3%A9ation-nouveau-b%C3%A9n%C3%A9ficiaire
> (5) UX création nouveau bénéficiaire

- config/packages/dev/monolog.yaml
- config/packages/prod/monolog.yaml
- config/packages/test/monolog.yaml
- src/Entity/Interface/LogActivitySubscriberInterface.php
- src/EventSubscriber/Logs/LoginSubscriber.php
- src/EventSubscriber/Logs/PersonalDataSubscriber.php
- src/EventSubscriber/Logs/RelaySubscriber.php
- src/EventSubscriber/Logs/UserSubscriber.php
- src/ServiceV2/ActivityLogger.php
- tests/v2/EventSubscriber/LoginSubscriberTest.php
- tests/v2/EventSubscriber/Logs/AbstractLogActivitySubscriberTest.php
- tests/v2/EventSubscriber/Logs/LoginSubscriberTest.php
- tests/v2/EventSubscriber/Logs/PersonalDataSubscriberTest.php
- tests/v2/EventSubscriber/Logs/RelaySubscriberTest.php
- tests/v2/EventSubscriber/Logs/TestLogActivitySubscriberInterface.php
- tests/v2/EventSubscriber/Logs/UserSubscriberTest.php
[Ticket](https://trello.com/c/0C4i9vls/3566-8-nouveaux-logs-cfn)
> Nouveaux logs CFN

- config/packages/admin.yaml
- config/validator/user.yml
- src/Api/Dto/BeneficiaryDto.php
- src/Entity/Beneficiaire.php
- src/Entity/Centre.php
- src/Entity/Membre.php
- src/Validator/Constraints/UniqueExternalLink.php
- src/Validator/Constraints/UniqueExternalLinkValidator.php
https://trello.com/c/Vq3eYjCX/3587-8-rosalie-fix-retours-fr%C3%A9d%C3%A9ric-d%C3%A9tails-dans-le-ticket
> (8) ROSALIE - Fix retours Frédéric (détails dans le ticket)

- assets/js/angular/document.js
- templates/app/document/list.html.twig
[Ticket](https://trello.com/c/uObk9YZp/3573-2-enqu%C3%AAte-2h-preprod-erreur-affichage-de-linscription-%C3%A0-la-newsletter)
> Erreur affichage de l'inscription à la newsletter

- assets/controllers/alert_controller.js
- assets/css/appV2/theme.scss
- src/Entity/Membre.php
- src/Repository/BeneficiaireRepository.php
- templates/v2/professional/_action_dropdown.html.twig
- templates/v2/professional/_filter_beneficiaries_form.html.twig
- templates/v2/vault/relay/_address_column.html.twig
> Retours validation espace pro v2

- config/packages/sonata_admin.yaml
- templates/sonata/base_list.html.twig
[Ticket](https://trello.com/c/VFMs6m7w/3605-2-en-tant-quadmin-je-ne-peux-pas-supprimer-tous-les-%C3%A9l%C3%A9ments-sur-les-pages-notes-documents-dossiers-evenements-contacts-sms-de-r)
> En tant qu'admin, je ne peux pas supprimer "tous les éléments" sur les pages de l'admin

- templates/v2/user_affiliation/beneficiary/_disaffiliate_card.html.twig
- templates/v2/vault/components/_action_dropdown_item.html.twig
[Ticket1](https://trello.com/c/ZwnyD94x/3519-1-mettre-%C3%A0-disposition-la-page-qui-liste-les-b%C3%A9n%C3%A9ficiaires)
[Ticket2](https://trello.com/c/ogEq6e3l/3635-sur-la-page-https-preprodreconnectfr-beneficiary-20124-disaffiliate-les-adresses-sont-sous-la-forme-num%C3%A9ro-rue-code-postal-ville)
> Retour de validation : Désaffiliation bénéficiaire

- config/packages/security.yaml
- src/Controller/MainController.php
- templates/homeV2/base.html.twig
- templates/homeV2/pages/components/_reconnect_information.html.twig
- templates/homeV2/pages/contact.html.twig
- templates/homeV2/pages/newsletter_confirmation.html.twig
- templates/homeV2/sections/_newsletter_confirmation_section.html.twig
- templates/homeV2/sections/_newsletter_contact_us_section.html.twig
- templates/homeV2/sections/our-solutions-section.html.twig
- templates/homeV2/templates/contact-us-template.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/goFT7WH4/3641-3-page-de-confirmation-dinscription-%C3%A0-la-newsletter)
> Page de confirmation d'inscription à la newsletter

- assets/controllers/ajax_alert_controller.js
- assets/controllers/alert_controller.js
- assets/controllers/disaffiliate_user_controller.js
- assets/controllers/helpers/swal_helper.js
- templates/v2/user_affiliation/beneficiary/_disaffiliate_card.html.twig
- templates/v2/user_affiliation/beneficiary/disaffiliate_beneficiary.html.twig
- templates/v2/user_creation/beneficiary/_abort_button.html.twig
- templates/v2/vault/components/_action_dropdown_item.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/KOW2ZHF9/3645-2-retours-page-https-preprodreconnectfr-beneficiary-20124-disaffiliate)
> Retours page https://preprod.reconnect.fr/beneficiary/20124/disaffiliate

- assets/js/angular/document.js
- templates/app/document/modal_information.html.twig
[Ticket](https://trello.com/c/AebLuKnQ/3643-52-le-champ-d%C3%A9pos%C3%A9-par-dans-les-informations-dun-document-depuis-un-compte-b%C3%A9n%C3%A9f-est-vide)
> Le champ "Déposé par" dans les informations d'un document, depuis un compte bénéf, est vide

- src/ControllerV2/BeneficiaryAffiliationController.php
- src/Entity/Membre.php
- templates/v2/professional/_beneficiaries_list_row.html.twig
- templates/v2/user_affiliation/beneficiary/_disaffiliate_card.html.twig
- templates/v2/vault/components/_action_dropdown_item.html.twig
- tests/v2/Controller/BeneficiaryAffiliationController/DisaffiliateTest.php
- tests/v2/EventSubscriber/Logs/AbstractLogActivitySubscriberTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/FbVtMm6D/3660-3-weirdiness-sur-la-page-https-preprodreconnectfr-beneficiary-12490-disaffiliate)
> Weirdiness sur la page https://preprod.reconnect.fr/beneficiary/12490/disaffiliate

- templates/v2/professional/_action_dropdown.html.twig
- templates/v2/user_affiliation/beneficiary/disaffiliate_beneficiary.html.twig
- templates/v2/vault/components/_action_dropdown_item.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
> Update disaffiliation trans

- src/Controller/PrivateResettingController.php
> :lock: Fix pro reset password

- src/ControllerV2/FolderController.php
- src/ManagerV2/DocumentManager.php
- src/Repository/DocumentRepository.php
- src/Repository/DossierRepository.php
- templates/v2/vault/document/_card.html.twig
- templates/v2/vault/document/_list.html.twig
- templates/v2/vault/folder/_card.html.twig
[Ticket](https://trello.com/c/REm5oXQH/3454-3-v2-on-ne-peut-pas-modifier-la-vibisilit%C3%A9-dun-doc-ou-dun-dossier-qui-comporte-un-dossier-parent)
> (3) [v2] On ne peut pas modifier la vibisilité d'un doc ou d'un dossier qui comporte un dossier parent

- src/ControllerV2/DocumentController.php
- src/ControllerV2/FolderController.php
> :lock: [Pro] Hide docs for pros

- assets/controllers/ajax_alert_controller.js
- assets/controllers/alert_controller.js
- assets/controllers/helpers/swal_helper.js
- templates/v2/notifications/relay_invitation_notification.html.twig
[Ticket](https://trello.com/c/ChmCmWv9/3658-5-harmonisation-des-boutons-sur-les-modales-dalerte)
> Harmonisation des boutons sur les modales d'alerte

- src/ServiceV2/ResettingService.php
- templates/sonata/base_list.html.twig
- translations/messages.fr.yml
[Ticket](https://trello.com/c/5qo5qGGn/3680-2-enqu%C3%AAte-2h-en-tant-quadmin-je-ne-peux-pas-s%C3%A9lectionner-la-totalit%C3%A9-des-donn%C3%A9es)
> En tant qu'admin, je ne peux pas sélectionner la totalité des données

- translations/messages.ar.yml
- translations/messages.de.yml
- translations/messages.en.yml
- translations/messages.es.yml
- translations/messages.fr.yml
- translations/messages.it.yml
- translations/messages.prs.yml
- translations/messages.ps.yml
- translations/messages.ru.yml
> :globe_with_meridians: [Translations] First CLI pull from Crowdon

- assets/controllers/mailjet_controller.js
- assets/css/homeV2/main.scss
- src/Controller/MainController.php
- templates/homeV2/templates/contact-us-template.html.twig
[Ticket](https://trello.com/c/lTFtGbsA/3617-enqu%C3%AAte-5h-nouvelle-newsletter-cfn)
> [Enquête 5h] Nouvelle newsletter CFN

- composer.json
- composer.lock
- src/ControllerV2/BeneficiaryResetPasswordController.php
- src/ControllerV2/ResetPasswordController.php
- src/EventSubscriber/AddFormattedPhoneSubscriber.php
- src/FormV2/ResetPassword/BeneficiaryRequest/ResetPasswordSmsFormModel.php
- src/FormV2/ResetPassword/BeneficiaryRequest/ResetPasswordSmsFormType.php
- src/FormV2/ResetPassword/PublicRequest/ResetPasswordCheckSMSFormModel.php
- src/FormV2/ResetPassword/PublicRequest/ResetPasswordRequestFormModel.php
- src/FormV2/ResetPassword/PublicRequest/ResetPasswordRequestFormType.php
- src/FormV2/ResetPassword/PublicRequest/ResetPasswordSmsCheckFormType.php
- src/ServiceV2/ResettingService.php
- templates/v2/common/_hide_show_password_input.html.twig
- templates/v2/reset_password/beneficiary/_choice_cards.html.twig
- templates/v2/reset_password/beneficiary/choice.html.twig
- templates/v2/reset_password/beneficiary/reset_password_layout.html.twig
- templates/v2/reset_password/beneficiary/sms.html.twig
- templates/v2/reset_password/public/request.html.twig
- tests/v2/Controller/BeneficiaryResetPasswordController/SMSTest.php
- tests/v2/Controller/ResetPasswordControllerTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/8w26Z4G2/3730-7-pro-r%C3%A9initialisation-du-mdp-b%C3%A9n%C3%A9ficiaire-par-sms)
> [PRO] Réinitialisation du mdp bénéficiaire - Par sms

- assets/controllers/helpers/swal_helper.js
- templates/v2/notifications/relay_invitation_notification.html.twig
- templates/v2/vault/components/_action_dropdown.html.twig
- templates/v2/vault/components/_action_dropdown_item.html.twig
[Ticket](https://trello.com/c/ChmCmWv9/3658-5-harmonisation-des-boutons-sur-les-modales-dalerte)
> Harmonisation des boutons sur les modales d'alerte - Prise en compte des retours

- tests/v2/AuthenticatedKernelTestCase.php
- tests/v2/Manager/DocumentManager/CreateDocumentFromFileTest.php
> :white_check_mark: [DocumentManager] Add tests

- assets/controllers/lang_selector_controller.js
- assets/js/homeV2/openstreetmap-marker-generator.js
- assets/js/language-selector.js
- config/packages/security.yaml
- config/routes.yaml
- config/routing/main/routing.yml
- src/Controller/MainController.php
- src/ControllerV2/OldResetPasswordController.php
- src/ControllerV2/ResetPasswordController.php
- tests/v2/Controller/ResetPasswordControllerTest.php
- tests/v2/Smoke/Public/ApplicationAvailabilityFunctionalTest.php
[Ticket](https://trello.com/c/MdKWNQJk/2742-3-pr%C3%A9fixer-toutes-les-urls-publiques-par-public)
> Préfixer les URLs publiques par /public

- src/ControllerV2/BeneficiaryResetPasswordController.php
- src/Entity/Beneficiaire.php
- src/FormV2/ResetPassword/BeneficiaryRequest/ResetPasswordSecretAnswerFormModel.php
- src/FormV2/ResetPassword/BeneficiaryRequest/ResetPasswordSmsFormType.php
- src/ServiceV2/ResettingService.php
- tests/Factory/UserFactory.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/NcGPUQLS/3721-5-pro-r%C3%A9initialisation-du-mdp-b%C3%A9n%C3%A9ficiaire-page-choix-de-la-m%C3%A9thode)
[Ticket](https://trello.com/c/tsGcuDKB/3722-3-pro-r%C3%A9itinialisation-du-mdp-b%C3%A9n%C3%A9ficiaire-par-email)
[Ticket](https://trello.com/c/8w26Z4G2/3730-7-pro-r%C3%A9initialisation-du-mdp-b%C3%A9n%C3%A9ficiaire-par-sms)
[Ticket](https://trello.com/c/OktAzyNm/3723-4-pro-r%C3%A9itinialisation-du-mdp-b%C3%A9n%C3%A9ficiaire-par-question-secr%C3%A8te)
> [PRO] Réinitialisation du mdp bénéficiaire - Traitement des retours

- .github/workflows/symfony.yaml
> :construction_worker: [CI - PHP ] Run test on multiple versions

- src/Controller/PrivateResettingController.php
- templates/user/resetting/private/index.html.twig
- tests/v2/Controller/PrivateResettingControllerTest.php
[Ticket](https://trello.com/c/cEGVYs1K/3700-2-remplacement-page-reset-random)
> Remplacement page RESET RANDOM

- src/Entity/MembreCentre.php
- src/Entity/User.php
- src/Entity/UserCentre.php
- src/Security/VoterV2/ProVoter.php
[Ticket](https://trello.com/c/mPvZ86cn/3738-8-nouvelle-page-recherche-pro)
> (8) Nouvelle page recherche pro

- src/ServiceV2/ResettingService.php
[Ticket](https://trello.com/c/tsGcuDKB/3722-3-pro-r%C3%A9itinialisation-du-mdp-b%C3%A9n%C3%A9ficiaire-par-email)
> [PRO] Réitinialisation du mdp bénéficiaire - Par email - bugfix

- translations/messages.fr.yml
> :recycle: [Trans] Fix trans

- src/ServiceV2/NotificationService.php
> :bug: [RelayInvitation] Fix case relay has no address

- templates/v2/vault/components/_action_dropdown.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/ChmCmWv9/3658-5-harmonisation-des-boutons-sur-les-modales-dalerte)
> Harmonisation des boutons sur les modales d'alerte - nouveaux fix

- src/Controller/SecurityController.php
- src/Entity/User.php
- templates/v2/common/_button.html.twig
- templates/v2/common/_modal.html.twig
- templates/v2/common/_notification.html.twig
> :bug: [SecretQuestion] Fix redirection hiding modal

- templates/v2/user_affiliation/beneficiary/_disaffiliate_card.html.twig
[Ticket](https://trello.com/c/ChmCmWv9/3658-5-harmonisation-des-boutons-sur-les-modales-dalerte)
> Harmonisation des boutons sur les modales d'alerte - nouveaux retours

- src/FormV2/ChangePasswordFormType.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/q3xBvDtr/3747-5-bugs-post-upgrade)
> Bugs post upgrade - nouveaux retours

- src/HelperEntity/Notification.php
- src/HelperEntity/NotificationForm.php
- src/ServiceV2/NotificationService.php
- templates/v2/common/_notification.html.twig
- templates/v2/user/delete.html.twig
- translations/messages.de.yml
- translations/messages.en.yml
- translations/messages.es.yml
- translations/messages.fr.yml
- translations/messages.it.yml
[Ticket](https://trello.com/c/PjIGJEvr/3699-8-les-4529-cfn-sans-question-secr%C3%A8te-sont-invit%C3%A9s-%C3%A0-en-cr%C3%A9er-une-%C3%A0-leur-prochaine-connexion-au-cfn)
> Les 4529 CFN sans question secrète sont invités à en créer une à leur prochaine connexion au CFN

- templates/v2/professional/_beneficiaries_list_row.html.twig
> :sparkles: [BeneficiaryResetPassword] Enable new reset password feature

- .husky/pre-commit
> :sparkles: [Husky] Add hook to test files on precommit

- templates/homeV2/templates/contact-us-template.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/Zaqlg3Bc/3782-2-enqu%C3%AAte-2h-finaliser-inscription-newsletter-avec-ce-que-mailjet-a-r%C3%A9par%C3%A9)
> Finaliser inscription newsletter avec ce que mailjet a réparé

- package.json
- yarn.lock
> :arrow_up: [Node] Remove eslint rule

- assets/css/forms_custom.less
- src/ControllerV2/ProController.php
- src/FormV2/UserCreation/CreateUserType.php
- templates/v2/common/_button.html.twig
- templates/v2/common/_card_with_form.html.twig
- templates/v2/common/_form_actions.html.twig
- templates/v2/pro/create/create.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/BrKL6EjM/3739-3-nouvelle-page-cr%C3%A9ation-pro)
> nouvelle-page-création-pro

- templates/user/membre-membre/membresCentre.html.twig
> :globe_with_meridians: [Tooltip] Fix missing translation

- src/ControllerV2/UserController.php
- src/EventSubscriber/UserCreationSubscriber.php
- src/FormV2/UserSettingsType.php
- src/Repository/UserRepository.php
- templates/v2/user/_settings_form_block.html.twig
- templates/v2/user/_user_settings_form.html.twig
- templates/v2/user/settings.html.twig
- tests/v2/Listener/UserCreationListenerTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Etape 1](https://trello.com/c/eJFGVydo/3812-3-formatage-username-%C3%A9tape-1-modifier-la-query-qui-check-les-homonymes)
[Etape 2](https://trello.com/c/9TuXyWt3/3813-1-formatage-username-%C3%A9tape-2-modifier-leventlistener)
[Etape 3](https://trello.com/c/vcFCvqVa/3814-52-formatage-username-%C3%A9tape-3-notifier-lutilisateur-lorsquil-modifie-des-informations-qui-ont-un-impact-sur-son-username)
[Etape 4](https://trello.com/c/hnxzH9pX/3820-1-formatage-username-%C3%A9tape-4-sur-la-page-des-settings-pro-retirer-le-champ-username)
> Formatage Username 

- translations/messages.en.yml
> :bug: [trans] Fix dupplicated trans

- src/Controller/SecurityController.php
- src/ControllerV2/HomeController.php
- templates/v2/beneficiary/home/_nav_item.html.twig
- templates/v2/beneficiary/home/home.html.twig
- tests/v2/Smoke/Beneficiary/BeneficiaryApplicationAvailabilityFunctionalTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/IxccUTwa/3818-3-nouvelle-page-daccueil-c%C3%B4t%C3%A9-b%C3%A9n%C3%A9ficiaire)
> (3) Nouvelle page d'accueil côté bénéficiaire

- assets/controllers/conditional_field_controller.js
- src/ControllerV2/RosalieInteroperabilityController.php
- src/ServiceV2/BeneficiaryClientLinkService.php
- src/ServiceV2/RosalieService.php
- templates/v2/common/_card.html.twig
- templates/v2/common/_link_button.html.twig
- templates/v2/user_creation/beneficiary/_download_terms_of_use.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- templates/v2/user_creation/beneficiary/_step_5_rows.html.twig
- templates/v2/user_creation/beneficiary/_summary_row.html.twig
[Ticket](https://trello.com/c/6tm7ocMO/3844-3-cr%C3%A9ation-dun-b%C3%A9n%C3%A9ficiaire-par-un-pro)
> Création d'un bénéficiaire par un pro

- src/ControllerV2/HomeController.php
- templates/v2/vault/nav/_nav_item.html.twig
- templates/v2/vault/standard_layout.html.twig
- translations/messages.fr.yml
[Ticket](https://trello.com/c/hHaHvu8n/3825-2-maj-bandeau-page-docs-events-contacts-notes-relays-dun-b%C3%A9n%C3%A9f)
> (2) MAJ bandeau page docs, events, contacts, notes, relays d'un bénéf

- templates/v2/common/_card_with_form.html.twig
- templates/v2/common/_form_actions.html.twig
- templates/v2/pro/create/_search_card.html.twig
- templates/v2/pro/create/create.html.twig
- templates/v2/pro/create/index.html.twig
- templates/v2/user/affiliation/invite.html.twig
- tests/v2/Controller/ProController/CreateTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/Y6Vg973C/3845-3-cr%C3%A9ation-dun-pro-par-un-pro)
> (3) Création d'un pro par un pro

- src/Admin/DocumentAdmin.php
- src/Admin/DossierAdmin.php
[Ticket](https://trello.com/c/XkBlAxeR/3855-1-admin-cfn-dossiers-et-docs-afficher-le-parent-folder-id)
> Admin CFN - Dossiers et docs, afficher le parent folder id

- templates/v2/pro/list/_update_permission_button.html.twig
- templates/v2/pro/list/professionals.html.twig
- translations/messages.fr.yml
[Ticket](https://trello.com/c/oHa0mEtv/3848-05-lexique-page-https-preprodreconnectfr-pro)
> (0.5) Lexique page https://preprod.reconnect.fr/pro

- assets/css/appV2/form.scss
- src/FormV2/FilterUser/FilterUserType.php
- templates/v2/users_list/components/_filter_subjects_form.html.twig
[Ticket](https://trello.com/c/TFT08tdY/3860-1-chercher-sur-https-reconnectfr-beneficiaries-et-https-reconnectfr-pro)
> "Chercher" sur https://reconnect.fr/beneficiaries et https://reconnect.fr/pro

- config/doctrine/Beneficiaire.orm.yml
- src/Controller/Rest/BeneficiaireRestController.php
- src/Controller/Rest/BeneficiaireRestV2Controller.php
- src/Controller/UserCreationController.php
- src/Entity/Beneficiaire.php
- src/Migrations/Version20230717091659.php
[Ticket](https://trello.com/c/wKXHyogw/3865-1-affilier-benef-existant-si-le-b%C3%A9n%C3%A9f-a-indiqu%C3%A9-un-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-il-peut-valider-laffiliation-par-sms-pr%C3%A9paration)
> (1) [Affilier benef existant] Si le bénéf a indiqué un numéro de téléphone, il peut valider l'affiliation par SMS (préparation)

- templates/v2/user_creation/beneficiary/create_beneficiary.html.twig
- templates/v2/user_creation/beneficiary/create_beneficiary_step.html.twig
[Ticket](https://trello.com/c/37FCDJhe/3871-1-preprod-uniquement-icones-des-pages-ajout-b%C3%A9n%C3%A9f-disparues)
> (1) PREPROD UNIQUEMENT - icones des pages ajout bénéf disparues

- templates/v2/pro/list/_update_permission_button.html.twig
- templates/v2/pro/list/professionals.html.twig
- translations/messages.fr.yml
[Ticket](https://trello.com/c/oHa0mEtv/3848-05-lexique-page-https-preprodreconnectfr-pro)
> [Main] (0.5) Lexique page https://preprod.reconnect.fr/pro

- src/Admin/DocumentAdmin.php
- src/Admin/DossierAdmin.php
[Ticket](https://trello.com/c/XkBlAxeR/3855-1-admin-cfn-dossiers-et-docs-afficher-le-parent-folder-id)
> [Main] Admin CFN - Dossiers et docs, afficher le parent folder id

- templates/v2/common/_card_with_form.html.twig
- templates/v2/common/_form_actions.html.twig
- templates/v2/pro/create/_search_card.html.twig
- templates/v2/pro/create/create.html.twig
- templates/v2/pro/create/index.html.twig
- templates/v2/user/affiliation/invite.html.twig
- tests/v2/Controller/ProController/CreateTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/Y6Vg973C/3845-3-cr%C3%A9ation-dun-pro-par-un-pro)
> [Main] (3) Création d'un pro par un pro

- templates/v2/user/disaffiliation/disaffiliate.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/W9qDmwj4/3851-1-d%C3%A9saffilier-un-membre-professionnel-dun-relais)
> [Main] Désaffilier un membre/professionnel d'un relais

- src/ControllerV2/HomeController.php
- templates/v2/vault/nav/_nav_item.html.twig
- templates/v2/vault/standard_layout.html.twig
- translations/messages.fr.yml
[Ticket](https://trello.com/c/hHaHvu8n/3825-2-maj-bandeau-page-docs-events-contacts-notes-relays-dun-b%C3%A9n%C3%A9f)
> [Main] (2) MAJ bandeau page docs, events, contacts, notes, relays d'un bénéf

- src/Controller/SecurityController.php
- src/ControllerV2/HomeController.php
- templates/v2/base.html.twig
- templates/v2/beneficiary/home/_nav_item.html.twig
- templates/v2/beneficiary/home/home.html.twig
- tests/v2/Smoke/Beneficiary/BeneficiaryApplicationAvailabilityFunctionalTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/IxccUTwa/3818-3-nouvelle-page-daccueil-c%C3%B4t%C3%A9-b%C3%A9n%C3%A9ficiaire)
> [Main] (3) Nouvelle page d'accueil côté bénéficiaire

- assets/css/appV2/form.scss
- src/FormV2/FilterUser/FilterUserType.php
- templates/v2/users_list/components/_filter_subjects_form.html.twig
[Ticket](https://trello.com/c/TFT08tdY/3860-1-chercher-sur-https-reconnectfr-beneficiaries-et-https-reconnectfr-pro)
> [Main] "Chercher" sur https://reconnect.fr/beneficiaries et https://reconnect.fr/pro

- assets/controllers/conditional_field_controller.js
- src/ControllerV2/RosalieInteroperabilityController.php
- src/ServiceV2/BeneficiaryClientLinkService.php
- src/ServiceV2/RosalieService.php
- templates/v2/common/_card.html.twig
- templates/v2/common/_link_button.html.twig
- templates/v2/user_creation/beneficiary/_download_terms_of_use.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- templates/v2/user_creation/beneficiary/_step_5_rows.html.twig
- templates/v2/user_creation/beneficiary/_summary_row.html.twig
[Ticket](https://trello.com/c/6tm7ocMO/3844-3-cr%C3%A9ation-dun-b%C3%A9n%C3%A9ficiaire-par-un-pro)
> [Main] Création d'un bénéficiaire par un pro

- config/doctrine/Beneficiaire.orm.yml
- src/Controller/Rest/BeneficiaireRestController.php
- src/Controller/Rest/BeneficiaireRestV2Controller.php
- src/Controller/UserCreationController.php
- src/Entity/Beneficiaire.php
- src/Migrations/Version20230717091659.php
[Ticket 1](https://trello.com/c/wKXHyogw/3865-1-affilier-benef-existant-si-le-b%C3%A9n%C3%A9f-a-indiqu%C3%A9-un-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-il-peut-valider-laffiliation-par-sms-pr%C3%A9paration)
[Ticket 2](https://trello.com/c/yZFsQLC4/3835-8-affilier-benef-existant-si-le-b%C3%A9n%C3%A9f-a-indiqu%C3%A9-un-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-il-peut-valider-laffiliation-par-sms-feature)
[Ticket 3](https://trello.com/c/03Y3vfIO/3864-3-affilier-benef-existant-si-le-b%C3%A9n%C3%A9f-a-indiqu%C3%A9-un-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-il-peut-valider-laffiliation-par-sms-tests)
> [Main] [Affilier benef existant] Si le bénéf a indiqué un numéro de téléphone, il peut valider l'affiliation par SMS

- src/ControllerV2/UserController.php
- src/EventSubscriber/UserCreationSubscriber.php
- src/FormV2/UserSettingsType.php
- src/Repository/UserRepository.php
- templates/v2/user/_settings_form_block.html.twig
- templates/v2/user/_user_settings_form.html.twig
- templates/v2/user/settings.html.twig
- tests/v2/Listener/UserCreationListenerTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Etape 1](https://trello.com/c/eJFGVydo/3812-3-formatage-username-%C3%A9tape-1-modifier-la-query-qui-check-les-homonymes)
[Etape 2](https://trello.com/c/9TuXyWt3/3813-1-formatage-username-%C3%A9tape-2-modifier-leventlistener)
[Etape 3](https://trello.com/c/vcFCvqVa/3814-52-formatage-username-%C3%A9tape-3-notifier-lutilisateur-lorsquil-modifie-des-informations-qui-ont-un-impact-sur-son-username)
[Etape 4](https://trello.com/c/hnxzH9pX/3820-1-formatage-username-%C3%A9tape-4-sur-la-page-des-settings-pro-retirer-le-champ-username)
> [Main] Formatage Username

- src/Controller/AnnexeController.php
- templates/homeV2/footer.html.twig
[Ticket](https://trello.com/c/06nJ7mzd/3873-2-home-les-liens-du-bas-de-page-ne-m%C3%A8nent-vers-rien)
> (2) [HOME] Les liens du bas de page ne mènent vers rien

- src/Controller/MainController.php
- tests/v2/Smoke/Public/ApplicationAvailabilityFunctionalTest.php
> :bug: Fix public route redirections

- src/ControllerV2/RosalieInteroperabilityController.php
- templates/v2/rosalie/add_si_siao_number.html.twig
- templates/v2/user_affiliation/beneficiary/_relays_form_secret_question.html.twig
- templates/v2/user_affiliation/beneficiary/_relays_form_sms_code.html.twig
- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
- tests/v2/Controller/RosalieInteroperabilityController/AddSiSiaoNumberTest.php
[Ticket](https://trello.com/c/QOHdlKuV/3852-5-affiliation-cfn-existant-ajout-champ-si-siao)
> (5) Affiliation CFN existant : ajout champ SI SIAO

- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
[Ticket](https://trello.com/c/QOHdlKuV/3852-5-affiliation-cfn-existant-ajout-champ-si-siao)
> (5) Affiliation CFN existant : ajout champ SI SIAO - FIX UI

- config/packages/security.yaml
- src/ControllerV2/OldResetPasswordController.php
- tests/v2/Smoke/Public/ApplicationAvailabilityFunctionalTest.php
> [Main] :bug: [App/reset-password] Fix 404 from mobile app

- config/packages/security.yaml
- src/ControllerV2/OldResetPasswordController.php
- tests/v2/Smoke/Public/ApplicationAvailabilityFunctionalTest.php
> :bug: [App/reset-password] Fix 404 from mobile app

- src/Controller/MainController.php
- tests/v2/Smoke/Public/ApplicationAvailabilityFunctionalTest.php
> [Main] :bug: Fix public route redirections

- src/Admin/ContactAdmin.php
- src/Admin/DocumentAdmin.php
- src/Admin/DossierAdmin.php
- src/Admin/EvenementAdmin.php
- src/Admin/NoteAdmin.php
[Ticket](https://trello.com/c/9riMWcBI/3884-2-sur-les-notes-documents-dossiers-%C3%A9v%C3%A9nements-contacts-je-peux-filtrer-par-r%C3%A9gion-centre-li%C3%A9-%C3%A0)
> Sur les notes, documents, dossiers, événements, contacts --> je peux filtrer par Région (Centre lié à)

- src/Controller/SecurityController.php
- src/DataFixtures/v2/AdminFixture.php
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/DataFixtures/v2/MemberFixture.php
- templates/user/membre-beneficiaire/creationBeneficiaireStep6.html.twig
- templates/user/subject/doDoAjoutSubject.html.twig
- tests/Factory/UserFactory.php
- tests/v2/Controller/PrivateResettingControllerTest.php
- tests/v2/Controller/SecurityController/LoginEndTest.php
- tests/v2/Controller/SecurityController/RedirectUserTest.php
[Ticket](https://trello.com/c/gENWIe5O/3913-3-en-tant-que-pro-si-je-nai-ni-les-droits-de-gestion-benef-ni-les-droits-de-gestion-pro-je-r%C3%A9cup%C3%A8re-une-403-au-login)
> (3) En tant que pro, si je n'ai ni les droits de gestion benef, ni les droits de gestion pro, je récupère une 403 au login

- src/Admin/ContactAdmin.php
- src/Admin/DocumentAdmin.php
- src/Admin/DossierAdmin.php
- src/Admin/EvenementAdmin.php
- src/Admin/NoteAdmin.php
[Ticket](https://trello.com/c/9riMWcBI/3884-2-sur-les-notes-documents-dossiers-%C3%A9v%C3%A9nements-contacts-je-peux-filtrer-par-r%C3%A9gion-centre-li%C3%A9-%C3%A0)
> [Main] Sur les notes, documents, dossiers, événements, contacts --> je peux filtrer par Région (Centre lié à)

- src/Controller/SecurityController.php
- src/DataFixtures/v2/AdminFixture.php
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/DataFixtures/v2/MemberFixture.php
- templates/user/membre-beneficiaire/creationBeneficiaireStep6.html.twig
- templates/user/subject/doDoAjoutSubject.html.twig
- tests/Factory/UserFactory.php
- tests/v2/Controller/PrivateResettingControllerTest.php
- tests/v2/Controller/SecurityController/LoginEndTest.php
- tests/v2/Controller/SecurityController/RedirectUserTest.php
[Ticket](https://trello.com/c/gENWIe5O/3913-3-en-tant-que-pro-si-je-nai-ni-les-droits-de-gestion-benef-ni-les-droits-de-gestion-pro-je-r%C3%A9cup%C3%A8re-une-403-au-login)
> [Main] (3) En tant que pro, si je n'ai ni les droits de gestion benef, ni les droits de gestion pro, je récupère une 403 au login

- config/packages/security.yaml
- src/Controller/AnnexeController.php
[Ticket](https://trello.com/c/Gda2lK5t/3932-2-private-policy-google-play-qui-y-a-t-il-derri%C3%A8re-le-lien-https-wwwreconnectsocial-annexe-confidentialite-cs)
> PRIVATE POLICY & GOOGLE PLAY - Qui y a-t-il derrière le lien https://www.reconnect.social/annexe/confidentialite-cs

- config/packages/security.yaml
- src/Controller/AnnexeController.php
[Ticket](https://trello.com/c/Gda2lK5t/3932-2-private-policy-google-play-qui-y-a-t-il-derri%C3%A8re-le-lien-https-wwwreconnectsocial-annexe-confidentialite-cs)
> [Main] PRIVATE POLICY & GOOGLE PLAY - Qui y a-t-il derrière le lien https://www.reconnect.social/annexe/confidentialite-cs ?

- src/ControllerV2/ProController.php
- src/Repository/MembreRepository.php
[Ticket](https://trello.com/c/ceTMmmSR/3918-1-v2-recherche-pro-affiliation-je-ne-peux-pas-me-trouver-moi-m%C3%AAme)
> V2 - Recherche pro/affiliation : je ne peux pas me trouver moi-même

- src/ControllerV2/BeneficiaryAffiliationController.php
- src/ControllerV2/BeneficiaryCreationController.php
- src/ControllerV2/UserController.php
- templates/v2/user/affiliation/invite.html.twig
- templates/v2/user_creation/components/_relays_checkboxes.html.twig
[Ticket](https://trello.com/c/V2wASlhF/3953-2-v2-je-ne-peux-affilier-un-professionnel-quaux-centres-pour-lesquels-jai-les-acc%C3%A8s-en-gestion-des-membres)
> (2) V2 - Je ne peux affilier un professionnel qu'aux centres pour lesquels j'ai les accès en "Gestion des membres"

- src/ControllerV2/BeneficiaryAffiliationController.php
- src/ControllerV2/BeneficiaryCreationController.php
- src/ControllerV2/UserController.php
- templates/v2/user/affiliation/invite.html.twig
- templates/v2/user_creation/components/_relays_checkboxes.html.twig
[Ticket](https://trello.com/c/V2wASlhF/3953-2-v2-je-ne-peux-affilier-un-professionnel-quaux-centres-pour-lesquels-jai-les-acc%C3%A8s-en-gestion-des-membres)
> [Main] (2) V2 - Je ne peux affilier un professionnel qu'aux centres pour lesquels j'ai les accès en "Gestion des membres"

- src/ControllerV2/ProController.php
- src/Repository/MembreRepository.php
[Ticket](https://trello.com/c/ceTMmmSR/3918-1-v2-recherche-pro-affiliation-je-ne-peux-pas-me-trouver-moi-m%C3%AAme)
> [Main] V2 - Recherche pro/affiliation : je ne peux pas me trouver moi-même

- templates/v2/user_affiliation/beneficiary/_relays_form_sms_code.html.twig
- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- translations/messages.fr.yml
[Ticket 1](https://trello.com/c/deB3AbeC/3983-05-v2-affiliate-b%C3%A9n%C3%A9f-modifier-paragraphe)
[Ticket 2](https://trello.com/c/8yU35piF/3980-05-v2-page-pro-modifier-texte-s%C3%A9lectionnez-un-centre-pour-modifier-les-droits-dun-utilisateur)
[Ticket 3](https://trello.com/c/9uDxNGTw/3987-1-page-preprodreconnectfr-beneficiary-create-3-4-superposition-de-boutons)
[Ticket 4](https://trello.com/c/KTRcjOr5/3984-1-v2-affiliate-bénéf-heure-à-langlaise-à-mettre-à-la-française)
> :lipstick: [V2] Fix a few ui and translations issues

- src/Entity/SMS.php
- src/ServiceV2/NotificationService.php
- tests/v2/Service/NotificationServiceTest.php
[Ticket](https://trello.com/c/avBud0t6/3986-2-enregistrement-en-bdd-des-sms-de-rappels-envoy%C3%A9s)
> (2) Enregistrement en BDD des SMS de rappels envoyés

- src/Entity/SMS.php
- src/ServiceV2/NotificationService.php
- tests/v2/Service/NotificationServiceTest.php
[Ticket](https://trello.com/c/avBud0t6/3986-2-enregistrement-en-bdd-des-sms-de-rappels-envoy%C3%A9s)
> [Main] (2) Enregistrement en BDD des SMS de rappels envoyés

- templates/v2/user_affiliation/beneficiary/_relays_form_sms_code.html.twig
- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- translations/messages.fr.yml
[Ticket 1](https://trello.com/c/deB3AbeC/3983-05-v2-affiliate-b%C3%A9n%C3%A9f-modifier-paragraphe)
[Ticket 2](https://trello.com/c/8yU35piF/3980-05-v2-page-pro-modifier-texte-s%C3%A9lectionnez-un-centre-pour-modifier-les-droits-dun-utilisateur)
[Ticket 3](https://trello.com/c/9uDxNGTw/3987-1-page-preprodreconnectfr-beneficiary-create-3-4-superposition-de-boutons)
[Ticket 4](https://trello.com/c/KTRcjOr5/3984-1-v2-affiliate-bénéf-heure-à-langlaise-à-mettre-à-la-française)
> [Main] :lipstick: [V2] Fix a few ui and translations issues

- templates/v2/common/_hide_show_password_input.html.twig
[Ticket](https://trello.com/c/Wh4ecdQC/3982-5-v2-mot-de-passe-%C3%A0-la-cr%C3%A9ation-dun-professionnel-2)
> (5) V2 - Mot de passe à la création d'un professionnel - Retours

- config/validator/user.yml
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/FormV2/UserCreation/CreateBeneficiaryType.php
- tests/v2/Controller/BeneficiaryCreationController/BeneficiaryCreationStep1Test.php
- translations/validators/validators.en.yml
- translations/validators/validators.fr.yml
[Ticket](https://trello.com/c/7aUEqi18/3988-2-si-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-existant-d%C3%A9j%C3%A0)
> (2) Si numéro de téléphone existant déjà

- src/ControllerV2/UserController.php
- templates/v2/common/_hide_show_password_input.html.twig
[Ticket](https://trello.com/c/8bruBz4t/4021-1-si-confirmation-de-mot-de-passe-diff%C3%A9rent-du-mot-de-passe-sur-la-page-https-reconnectfr-user-settings)
> (1) Si confirmation de mot de passe différent du mot de passe sur la page https://reconnect.fr/user/settings

- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/jDmmaP91/3985-2-2h-v2-am%C3%A9liorations-https-preprodreconnectfr-beneficiary-affiliate)
> (2) [2h] V2 - Améliorations https://preprod.reconnect.fr/beneficiary/affiliate

- src/FormV2/UserAffiliation/SearchBeneficiaryType.php
- templates/v2/user_affiliation/beneficiary/_search_result.html.twig
- templates/v2/user_affiliation/beneficiary/affiliate_beneficiary_search.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- templates/v2/user_creation/beneficiary/_step_relays.html.twig
- templates/v2/user_creation/beneficiary/download_terms_of_use.html.twig
- tests/v2/Controller/BeneficiaryAffiliationController/SearchTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/yeRaDJ7p/4017-1-v2-page-https-preprodreconnectfr-beneficiary-affiliate-search-si-la-recherche-naboutit-pas)
[Ticket](https://trello.com/c/dRxOi2IV/4014-1-v2-page-r%C3%A9capitulatif-%C3%A0-la-cr%C3%A9ation-dun-nouveau-b%C3%A9n%C3%A9ficiaire-en-pr%C3%A9sence-%C3%A0-distance-ajouter-une-ligne-date-de-naissance)
[Ticket](https://trello.com/c/ZTNfxSwE/4016-1-v2-page-https-preprodreconnectfr-beneficiary-affiliate-search-rendre-le-nom-pr%C3%A9nom-et-date-de-naissance-obligatoires-afin-pour)
[Ticket](https://trello.com/c/dCvG3uv8/4020-05-v2-page-https-preprodreconnectfr-beneficiary-create-download-terms-of-use-20-modifier-le-bouton-confirmer-en-terminer)
[Ticket](https://trello.com/c/781ZIGQp/4018-1-v2-page-https-preprodreconnectfr-beneficiary-create-4-20) …
> [Main] Feature/v2 benef creation fixes

- src/ControllerV2/UserController.php
- templates/v2/common/_hide_show_password_input.html.twig
[Ticket](https://trello.com/c/8bruBz4t/4021-1-si-confirmation-de-mot-de-passe-diff%C3%A9rent-du-mot-de-passe-sur-la-page-https-reconnectfr-user-settings)
> [Main] (1) Si confirmation de mot de passe différent du mot de passe sur la page https://reconnect.fr/user/settings

- config/validator/user.yml
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/FormV2/UserCreation/CreateBeneficiaryType.php
- tests/v2/Controller/BeneficiaryCreationController/BeneficiaryCreationStep1Test.php
- translations/validators/validators.en.yml
- translations/validators/validators.fr.yml
[Ticket](https://trello.com/c/7aUEqi18/3988-2-si-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-existant-d%C3%A9j%C3%A0)
> [Main] (2) Si numéro de téléphone existant déjà

- templates/v2/common/_card_with_form.html.twig
- templates/v2/common/_hide_show_password_input.html.twig
[Ticket](https://trello.com/c/Wh4ecdQC/3982-5-v2-mot-de-passe-%C3%A0-la-cr%C3%A9ation-dun-professionnel)
> [Main] (5) V2 - Mot de passe à la création d'un professionnel

- src/FormV2/UserType.php
- tests/v2/Controller/UserController/SettingsTest.php
[Ticket](https://trello.com/c/AAJkPAxn/4022-3-si-je-modifie-mes-param%C3%A8tres-en-ajoutant-un-num%C3%A9ro-de-tel-qui-existe-d%C3%A9j%C3%A0)
>  (3) Si je modifie mes paramètres en ajoutant un numéro de tel qui existe déjà 

- templates/v2/user/disaffiliation/disaffiliate.html.twig
[Ticket](https://trello.com/c/O5JPzmlp/4030-2-page-https-preprodreconnectfr-user-29578-disaffiliate-choose-relay-probleme-mener-enqu%C3%AAte-sur-autres-choses-qui-auraient-dispa)
> (2) Page https://preprod.reconnect.fr/user/29578/disaffiliate/choose-relay

- src/ControllerV2/UserController.php
[Ticket](https://trello.com/c/N0AVMvMt/4047-2-si-jindique-un-mauvais-votre-mot-de-passe-actuel-peu-visible-sur-la-page-https-reconnectfr-user-settings)
> (2) Si j'indique un mauvais "Votre mot de passe actuel" --> peu visible sur la page https://reconnect.fr/user/settings

- templates/v2/user_affiliation/beneficiary/affiliate_beneficiary.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket 1](https://trello.com/c/SFJf5IbC/4067-1-page-https-preprodreconnectfr-beneficiary-affiliate-modifier-le-titre-en-ajouter-un-beneficiaire-enlever-nouveau-enlever-le-so)
[Ticket 2](https://trello.com/c/7Zm4RfVp/4068-05-page-https-reconnectfr-pro-create-home-ajouter-des-aux-titres-des-cartes)
> (0.5) Page https://reconnect.fr/pro/create/home ajouter des "?" aux titres des cartes

- src/ManagerV2/EventManager.php
- src/Repository/RappelRepository.php
- src/ServiceV2/NotificationService.php
- tests/v2/Service/NotificationServiceTest.php
[Ticket](https://trello.com/c/ExCc94aE/4071-1-envoi-sms-fix-rapide)
> (1) [Envoi SMS] Fix rapide

- src/Controller/MembreBeneficiaireController.php
- src/Controller/SecurityController.php
- templates/v2/beneficiary/list/beneficiaries.html.twig
- tests/v2/Controller/SecurityController/RedirectUserTest.php
- tests/v2/OldController/MembreBeneficiaireController/AjoutBeneficiaireSearchTest.php
[Ticket](https://trello.com/c/K2Hadsal/4061-05-mise-%C3%A0-dispo-de-toutes-les-nouvelles-pages-cr%C3%A9ation-b%C3%A9n%C3%A9f-v2-cg-pr%C3%A9venir-marie-lorsquon-le-met-en-prod-la-veille)
> Mise à dispo de toutes les nouvelles pages création bénéf V2

- src/Entity/Dossier.php
- tests/v2/Validator/FolderCircularDependencyConstraintTest.php
- translations/validators/validators.en.yml
- translations/validators/validators.fr.yml
> Add test to protect from circular dependency

- src/Admin/AssociationAdmin.php
- src/EventSubscriber/AssociationCreationSubscriber.php
[Ticket](https://trello.com/c/RBmi7dlz/4060-5-5-bug-%C3%A0-la-cr%C3%A9ation-dune-asso)
> Bug à la création d'une asso

- src/ControllerV2/UserController.php
- templates/v2/common/_button.html.twig
- templates/v2/common/_form_actions.html.twig
- templates/v2/pro/create/_search_card.html.twig
- templates/v2/user/delete.html.twig
- tests/v2/Controller/UserController/DeleteTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/yORoTBbI/3924-1-v2-supprimer-un-compte-pour-un-b%C3%A9n%C3%A9ficiaire)
> Supprimer un compte pour un bénéficiaire

- src/Command/ImportUserCommand.php
> :card_file_box: [Import] Add script to import users

- templates/v2/user_affiliation/beneficiary/affiliate_beneficiary.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket 1](https://trello.com/c/SFJf5IbC/4067-1-page-https-preprodreconnectfr-beneficiary-affiliate-modifier-le-titre-en-ajouter-un-beneficiaire-enlever-nouveau-enlever-le-so)
[Ticket 2](https://trello.com/c/7Zm4RfVp/4068-05-page-https-reconnectfr-pro-create-home-ajouter-des-aux-titres-des-cartes)
> [Main] (0.5) Page https://reconnect.fr/pro/create/home ajouter des "?" aux titres des cartes

- src/ControllerV2/UserController.php
- templates/v2/common/_button.html.twig
- templates/v2/common/_form_actions.html.twig
- templates/v2/pro/create/_search_card.html.twig
- templates/v2/user/delete.html.twig
- tests/v2/Controller/UserController/DeleteTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/yORoTBbI/3924-1-v2-supprimer-un-compte-pour-un-b%C3%A9n%C3%A9ficiaire)
> [Main] Supprimer un compte pour un bénéficiaire

- src/ControllerV2/UserController.php
[Ticket](https://trello.com/c/N0AVMvMt/4047-2-si-jindique-un-mauvais-votre-mot-de-passe-actuel-peu-visible-sur-la-page-https-reconnectfr-user-settings)
> [Main] (2) Si j'indique un mauvais "Votre mot de passe actuel" --> peu visible sur la page https://reconnect.fr/user/settings

- src/Entity/Traits/DeactivatableTrait.php
- src/ManagerV2/RelayManager.php
- tests/v2/Manager/RelayManager/RemoveUserFromRelayTest.php
[Ticket](https://trello.com/c/VOdJ6884/4029-3-v2-si-je-retire-un-professionnel-dun-relais-alors-quil-est-affili%C3%A9-%C3%A0-un-unique-relais-son-compte-membre-est-d%C3%A9sactiv%C3%A9)
> [Main] (3) V2 - Si je retire un professionnel d'un relais alors qu'il est affilié à un unique relais, son compte membre est désactivé

- src/FormV2/UserType.php
- tests/v2/Controller/UserController/SettingsTest.php
[Ticket](https://trello.com/c/AAJkPAxn/4022-3-si-je-modifie-mes-param%C3%A8tres-en-ajoutant-un-num%C3%A9ro-de-tel-qui-existe-d%C3%A9j%C3%A0)
> [Main] (3) Si je modifie mes paramètres en ajoutant un numéro de tel qui existe déjà

- templates/v2/user/disaffiliation/disaffiliate.html.twig
[Ticket](https://trello.com/c/O5JPzmlp/4030-2-page-https-preprodreconnectfr-user-29578-disaffiliate-choose-relay-probleme-mener-enqu%C3%AAte-sur-autres-choses-qui-auraient-dispa)
> [Main] (2) Page https://preprod.reconnect.fr/user/29578/disaffiliate/choose-relay 

- src/Command/ImportUserCommand.php
> [MAIN] :card_file_box: [Import] Add script to import users

- templates/v2/user_creation/beneficiary/download_terms_of_use.html.twig
[Ticket](https://trello.com/c/bsWiMtja/4041-2-v2-erreur-403-cr%C3%A9ation-new-b%C3%A9n%C3%A9f-quand-jai-aucun-droit)
> [Main] (2) V2 - Erreur 403 création new bénéf quand j'ai aucun droit

- src/Controller/MembreBeneficiaireController.php
- src/Controller/SecurityController.php
- templates/v2/beneficiary/list/beneficiaries.html.twig
- tests/v2/Controller/SecurityController/RedirectUserTest.php
- tests/v2/OldController/MembreBeneficiaireController/AjoutBeneficiaireSearchTest.php
[Ticket](https://trello.com/c/K2Hadsal/4061-05-mise-%C3%A0-dispo-de-toutes-les-nouvelles-pages-cr%C3%A9ation-b%C3%A9n%C3%A9f-v2-cg-pr%C3%A9venir-marie-lorsquon-le-met-en-prod-la-veille)
> [Main] Mise à dispo de toutes les nouvelles pages création bénéf V2 

- Makefile
- src/Controller/MembreController.php
- src/Controller/MembreMembreController.php
- templates/v2/header/header.html.twig
- templates/v2/pro/list/professionals.html.twig
- tests/v2/OldController/MembreMembreController/AjoutMembreSearchTest.php
[Ticket](https://trello.com/c/ESLmNEe0/4078-v2-mettre-%C3%A0-disposition-toutes-les-nouvelles-pages-li%C3%A9es-%C3%A0-la-gestion-des-pro)
> V2 - Mettre à disposition toutes les nouvelles pages liées à la gestion des pro

- src/DataFixtures/v2/BeneficiaryFixture.php
- src/Entity/User.php
- src/ManagerV2/RelayManager.php
- tests/v2/Controller/UserController/ToggleUserInvitationTest.php
[Ticket](https://trello.com/c/tz7aoSVU/4132-lorsque-je-cr%C3%A9e-un-nouveau-cfn-je-peux-acc%C3%A9der-au-cfn-dun-b%C3%A9n%C3%A9ficiaire-affili%C3%A9-%C3%A0-mon-centre-avant-quil-accepte-laffiliation)
> Lorsque je crée un nouveau CFN, je peux accéder au CFN d'un bénéficiaire affilié à mon centre avant qu'il accepte l'affiliation

- templates/v2/user/disaffiliation/disaffiliate.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/6pu7Na9p/4081-titre-page-https-reconnectfr-user-27507-disaffiliate-choose-relay-sil-sagit-dun-b%C3%A9n%C3%A9ficiaire)
> Titre page https://reconnect.fr/user/27507/disaffiliate/choose-relay s'il s'agit d'un bénéficiaire

- templates/v2/user/disaffiliation/disaffiliate.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/6pu7Na9p/4081-titre-page-https-reconnectfr-user-27507-disaffiliate-choose-relay-sil-sagit-dun-b%C3%A9n%C3%A9ficiaire)
> [Main] Titre page https://reconnect.fr/user/27507/disaffiliate/choose-relay s'il s'agit d'un bénéficiaire

- Makefile
- src/Controller/MembreController.php
- src/Controller/MembreMembreController.php
- templates/v2/header/header.html.twig
- templates/v2/pro/list/professionals.html.twig
- tests/v2/OldController/MembreMembreController/AjoutMembreSearchTest.php
[Ticket](https://trello.com/c/ESLmNEe0/4078-v2-mettre-%C3%A0-disposition-toutes-les-nouvelles-pages-li%C3%A9es-%C3%A0-la-gestion-des-pro)
> [Main] Mettre à disposition toutes les nouvelles pages liées à la gestion des pro

- src/DataFixtures/v2/BeneficiaryFixture.php
- src/Entity/User.php
- src/ManagerV2/RelayManager.php
- tests/v2/Controller/UserController/ToggleUserInvitationTest.php
[Ticket](https://trello.com/c/tz7aoSVU/4132-lorsque-je-crée-un-nouveau-cfn-je-peux-accéder-au-cfn-dun-bénéficiaire-affilié-à-mon-centre-avant-quil-accepte-laffiliation)
> [Main] Lorsque je crée un nouveau CFN, je peux accéder au CFN d'un bénéficiaire affilié à mon centre avant qu'il accepte l'affiliation

- src/EventSubscriber/UserCreationSubscriber.php
[Ticket](https://trello.com/c/Aj6ViQKG/4113-3-mails-coffre-fort-num%C3%A9rique-doublons-b%C3%A9n%C3%A9ficiaire-pourquoi-les-re%C3%A7oit-on-tous-en-double-%F0%9F%A4%AF)
> (3) Mails [Coffre-Fort Numérique] Doublons bénéficiaire : pourquoi les reçoit-on tous en double ? 🤯

- config/services.yaml
- src/DataFixtures/v2/MemberFixture.php
- src/Entity/MembreCentre.php
- src/ListenerV2/CreatorListener.php
- src/ListenerV2/DeactivatableListener.php
- src/ManagerV2/RelayManager.php
- tests/v2/Listener/CreatorListenerTest.php
- tests/v2/Listener/DeactivatableListenerTest.php
[Ticket](https://trello.com/c/sAtjVHY0/4140-5-affiliation-dun-pro-%C3%A0-un-relais-hic-avec-la-d%C3%A9saffiliation-qui-entraine-la-d%C3%A9sactivation)
> Affiliation d'un pro à un relais --> hic avec la désaffiliation qui entraine la désactivation

- src/EventSubscriber/UserCreationSubscriber.php
> [Main] (3) Mails [Coffre-Fort Numérique] Doublons bénéficiaire : pourquoi les reçoit-on tous en double ? 🤯

- config/services.yaml
- src/DataFixtures/v2/MemberFixture.php
- src/Entity/MembreCentre.php
- src/ListenerV2/CreatorListener.php
- src/ListenerV2/DeactivatableListener.php
- src/ManagerV2/RelayManager.php
- tests/v2/Listener/CreatorListenerTest.php
- tests/v2/Listener/DeactivatableListenerTest.php
[Ticket](https://trello.com/c/sAtjVHY0/4140-5-affiliation-dun-pro-%C3%A0-un-relais-hic-avec-la-d%C3%A9saffiliation-qui-entraine-la-d%C3%A9sactivation)
> [Main] Affiliation d'un pro à un relais --> hic avec la désaffiliation qui entraine la désactivation

- src/Entity/Attributes/BeneficiaryCreationProcess.php
- src/Entity/Beneficiaire.php
- src/Entity/Membre.php
- src/Entity/UserWithCentresInterface.php
- templates/v2/user_creation/beneficiary/create_beneficiary_step.html.twig
- tests/v2/Controller/BeneficiaryCreationController/BeneficiaryCreationNoRelaySelectedTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/nLn1tPjh/4165-5-si-je-clique-sur-confirmer-alors-que-je-nai-s%C3%A9lectionn%C3%A9-aucun-centre-message-de-validation)
> Si je clique sur "confirmer" alors que je n'ai sélectionné aucun centre, message de validation

- src/Entity/Attributes/BeneficiaryCreationProcess.php
- src/Entity/Beneficiaire.php
- src/Entity/Membre.php
- src/Entity/UserWithCentresInterface.php
- templates/v2/user_creation/beneficiary/create_beneficiary_step.html.twig
- tests/v2/Controller/BeneficiaryCreationController/BeneficiaryCreationNoRelaySelectedTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/nLn1tPjh/4165-5-si-je-clique-sur-confirmer-alors-que-je-nai-s%C3%A9lectionn%C3%A9-aucun-centre-message-de-validation)
> [Main] Si je clique sur "confirmer" alors que je n'ai sélectionné aucun centre, message de validation

- assets/css/appV2/form.scss
[Ticket](https://trello.com/c/sHxc3P74/4202-05-placeholder-t%C3%A9l%C3%A9phone-en-gris-clair)
> Placeholder téléphone en gris clair

- templates/homeV2/templates/login-form-template.html.twig
[Ticket](https://trello.com/c/Ilg6AjEW/4224-1-enqu%C3%AAte-1h-loeil-pour-checker-son-mot-de-passe-ne-fonctionne-pas)
> L'oeil pour checker son mot de passe ne fonctionne pas

- config/packages/monolog.yaml
[Ticket](https://trello.com/c/L4uy9sSC/4196-2-capacit%C3%A9-des-serveurs)
>  [Main] :wrench: [Logs] Rotate deprecation logs

- templates/homeV2/templates/login-form-template.html.twig
[Ticket](https://trello.com/c/Ilg6AjEW/4224-1-enqu%C3%AAte-1h-loeil-pour-checker-son-mot-de-passe-ne-fonctionne-pas)
> [Main] L'oeil pour checker son mot de passe ne fonctionne pas

- assets/css/appV2/form.scss
[Ticket](https://trello.com/c/sHxc3P74/4202-05-placeholder-t%C3%A9l%C3%A9phone-en-gris-clair)
> [Main] Placeholder téléphone en gris clair

- src/Command/FixFoldersCircularDependancyCommand.php
- src/Repository/DossierRepository.php
[Ticket](https://trello.com/c/W7IQyjXz/4227-2-enqu%C3%AAte-2h-dossiers-en-d%C3%A9pendances-circulaires)
> Dossiers en dépendances circulaires

- src/ControllerV2/BeneficiaryAffiliationController.php
- src/Entity/Subject.php
- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
> :sparkles: [Affiliate beneficiary] Display alert if no centers selected

- templates/v2/user_creation/components/_relays_checkbox.html.twig
> :lipstick: [Relays checkboxes] Redesign

- src/ControllerV2/BeneficiaryAffiliationController.php
- src/Entity/Subject.php
- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
[Ticket](https://trello.com/c/dmOAEUI1/4253-3-ajout-dun-pop-up-si-aucun-centre-s%C3%A9lectionn%C3%A9-%C3%A0-laffiliation-dun-b%C3%A9n%C3%A9ficiaire-qui-a-d%C3%A9j%C3%A0-un-cfn)
> [Main] :sparkles: [Affiliate beneficiary] Display alert if no centers selected

- src/Admin/MembreCentreAdmin.php
- src/ControllerV2/ProController.php
- src/ControllerV2/UserController.php
- src/DataFixtures/v2/MemberFixture.php
- src/Entity/MembreCentre.php
- src/ListenerV2/ProDefaultPermissionListener.php
- src/Security/HelperV2/UserHelper.php
- templates/v2/common/_button_with_loader.html.twig
- templates/v2/common/_button_with_loader_content.html.twig
- templates/v2/user_creation/components/_permissions_checkbox.html.twig
- templates/v2/user_creation/components/_permissions_checkboxes.html.twig
- templates/v2/user_creation/components/_relays_checkbox.html.twig
- templates/v2/user_creation/components/_relays_checkboxes.html.twig
- tests/v2/Controller/UserController/ToggleUserInvitationTest.php
- tests/v2/Entity/UserTest.php
- tests/v2/Listener/ProDefaultPermissionListenerTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/C5gKu3s8/4266-8-sur-la-page-daffiliation-dun-professionnel-%C3%A0-un-relais-je-peux-s%C3%A9lectionner-ses-r%C3%B4les-sp%C3%A9cifiquement)
> Sur la page d'affiliation d'un professionnel à un relais, je peux sélectionner ses rôles spécifiquement

- src/Command/DataChecker/CheckVaultsStorageCommand.php
- src/Command/DataExport/ExportDocumentsCommand.php
- src/Command/DataFixer/AddCreatorCenterCommand.php
- src/Command/DataFixer/FixCreatorUserCommand.php
- src/Command/DataFixer/StandardizePhoneNumbersCommand.php
- src/Command/DataFixer/UpdateAccessToDocumentsInFoldersCommand.php
- src/Command/DataImport/ImportBeneficiaireCommand.php
- src/Command/DataImport/ImportUserCommand.php
- src/Command/DataMigration/MigrateAuthorDataCommand.php
- src/Command/DataMigration/MigrateGestionnaireToMemberCommand.php
- src/Command/DataMigration/MigrateRosalieIdsToSiSiaoIdsCommand.php
- src/Entity/Beneficiaire.php
- src/Extension/CommonExtension.php
- src/Extension/DocumentExtension.php
- src/Provider/DocumentProvider.php
- src/Repository/BeneficiaireRepository.php
[Ticket](https://trello.com/c/6mVeiqKI/4246-5-enqu%C3%AAte-5h-la-capacit%C3%A9-de-stockage-indiqu%C3%A9e-ne-correspond-pas-au-poids-des-docs-stock%C3%A9s)
> (5) [Enquête 5h] La capacité de stockage indiquée ne correspond pas au poids des docs stockés #454

- src/ControllerV2/ProController.php
- src/Entity/MembreCentre.php
- src/Entity/User.php
- src/Security/VoterV2/ProRelayLinkVoter.php
- templates/v2/common/_button_with_loader.html.twig
- templates/v2/pro/list/_update_permission_button.html.twig
- templates/v2/user_creation/components/_relays_checkbox.html.twig
- tests/v2/Controller/ProController/TogglePermission.php
[Ticket](https://trello.com/c/9f985leX/4275-3-si-je-nai-pas-un-r%C3%B4le-je-ne-peux-pas-le-donner-%C3%A0-qqun)
> Si je n'ai pas un rôle, je ne peux pas le donner à qqun

- templates/v2/user_creation/beneficiary/_relays_card.html.twig
- templates/v2/user_creation/beneficiary/_step_relays.html.twig
- tests/v2/Listener/ProDefaultPermissionListenerTest.php
[Ticket](https://trello.com/c/TnwI6hth/4295-3-am%C3%A9lioration-visuelle-page-cr%C3%A9ation-b%C3%A9n%C3%A9ficiaire)
> Amélioration visuelle page création bénéficiaire

- templates/v2/user/affiliation/_invite_user_card.html.twig
- templates/v2/user/affiliation/invite.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/WwEwDTko/4284-am%C3%A9lioration-visuelle-page-dinvitation-pro-%C3%A0-un-centre)
> Amélioration visuelle page d'invitation pro à un centre -> vers affiliate/pro

- templates/v2/user_creation/beneficiary/_relays_card.html.twig
- templates/v2/user_creation/beneficiary/_step_relays.html.twig
- tests/v2/Listener/ProDefaultPermissionListenerTest.php
[Ticket](https://trello.com/c/TnwI6hth/4295-3-am%C3%A9lioration-visuelle-page-cr%C3%A9ation-b%C3%A9n%C3%A9ficiaire)
>  Amélioration visuelle page création bénéficiaire --> vers feature/affliate-pro

- Makefile
- src/ListenerV2/DeactivatableListener.php
[Ticket](https://trello.com/c/h4vn5bhV/4301-2-si-je-d%C3%A9saffilie-un-pro-dun-centre-alors-il-est-d%C3%A9sactiv%C3%A9-m%C3%AAme-sil-lui-reste-dautres-centres)
> Si je désaffilie un pro d'un centre, alors il est désactivé, même s'il lui reste d'autres centres

- src/ControllerV2/RosalieInteroperabilityController.php
[Ticket](https://trello.com/c/gLWOJM9Q/4306-2-rosalie-probl%C3%A8me-quand-on-arrive-sur-la-page)
> (2) Rosalie problème quand on arrive sur la page

- Makefile
- src/ListenerV2/DeactivatableListener.php
[Ticket](https://trello.com/c/h4vn5bhV/4301-2-si-je-d%C3%A9saffilie-un-pro-dun-centre-alors-il-est-d%C3%A9sactiv%C3%A9-m%C3%AAme-sil-lui-reste-dautres-centres)
> [Main] Si je désaffilie un pro d'un centre, alors il est désactivé, même s'il lui reste d'autres centres

- .env
- assets/bootstrap.js
- bin/phpunit
- composer.lock
- config/packages/api_platform.yaml
- config/packages/doctrine.yaml
- config/packages/notifier.yaml
- config/packages/translation.yaml
- phpunit.xml.dist
- src/Command/DataChecker/CheckVaultsStorageCommand.php
- src/Command/DataExport/ExportDocumentsCommand.php
- src/Command/DataFixer/AddCreatorCenterCommand.php
- src/Command/DataFixer/FixCreatorUserCommand.php
- src/Command/DataFixer/StandardizePhoneNumbersCommand.php
- src/Command/DataFixer/UpdateAccessToDocumentsInFoldersCommand.php
- src/Command/DataImport/ImportBeneficiaireCommand.php
- src/Command/DataImport/ImportUserCommand.php
- src/Command/DataMigration/MigrateAuthorDataCommand.php
- src/Command/DataMigration/MigrateGestionnaireToMemberCommand.php
- src/Command/DataMigration/MigrateRosalieIdsToSiSiaoIdsCommand.php
- src/Entity/Beneficiaire.php
- src/Extension/CommonExtension.php
- src/Extension/DocumentExtension.php
- src/ManagerV2/FolderManager.php
- src/Provider/DocumentProvider.php
- src/Repository/BeneficiaireRepository.php
- symfony.lock
> [Main] (5) [Enquête 5h] La capacité de stockage indiquée ne correspond pas au poids des docs stockés

- src/ControllerV2/RosalieInteroperabilityController.php
- templates/v2/rosalie/add_si_siao_number.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- templates/v2/user_creation/beneficiary/_step_5_rows.html.twig
- templates/v2/user_creation/beneficiary/_summary_row.html.twig
[Ticket](https://trello.com/c/G7Rzy1BO/4319-3-quand-je-cr%C3%A9e-un-b%C3%A9n%C3%A9ficiaire-je-peux-modifier-son-num%C3%A9ro-si-siao-%C3%A0-la-page-r%C3%A9cap)
> Quand je crée un bénéficiaire, je peux modifier son numéro SI-SIAO à la page récap

- src/Controller/Api/SwitchUserLocaleController.php
- src/Controller/Rest/BeneficiaireRestV2Controller.php
> [Main] :bug: [Create benef] Appli force accept

- src/Controller/Api/SwitchUserLocaleController.php
- src/Controller/Rest/BeneficiaireRestV2Controller.php
> :bug: [Create benef] Appli force accept

- src/ControllerV2/RosalieInteroperabilityController.php
- templates/v2/rosalie/add_si_siao_number.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- templates/v2/user_creation/beneficiary/_step_5_rows.html.twig
- templates/v2/user_creation/beneficiary/_summary_row.html.twig
[Ticket](https://trello.com/c/G7Rzy1BO/4319-3-quand-je-cr%C3%A9e-un-b%C3%A9n%C3%A9ficiaire-je-peux-modifier-son-num%C3%A9ro-si-siao-%C3%A0-la-page-r%C3%A9cap)
> Quand je crée un bénéficiaire, je peux modifier son numéro SI-SIAO à la page récap --> vers feature/rosalie-fix

- src/ControllerV2/RosalieInteroperabilityController.php
- src/Entity/Helper/BeneficiaryCheckOnRosalie.php
- src/ServiceV2/RosalieService.php
- tests/v2/Service/RosalieServiceTest.php
[Ticket](https://trello.com/c/YUYjNMSg/4307-5-rosalie-gestion-des-erreurs-potentielles-lors-dun-nom-pr%C3%A9nom-qui-ne-correspond-pas-au-num%C3%A9ro-si-siao)
> Rosalie gestion des erreurs potentielles lors d'un nom/prénom qui ne correspond pas au numéro SI-SIAO 

- src/ControllerV2/RosalieInteroperabilityController.php
- src/Entity/Helper/BeneficiaryCheckOnRosalie.php
- src/ServiceV2/RosalieService.php
- tests/v2/Service/RosalieServiceTest.php
[Ticket](https://trello.com/c/YUYjNMSg/4307-5-rosalie-gestion-des-erreurs-potentielles-lors-dun-nom-pr%C3%A9nom-qui-ne-correspond-pas-au-num%C3%A9ro-si-siao)
> Rosalie gestion des erreurs potentielles lors d'un nom/prénom qui ne correspond pas au numéro SI-SIAO => vers rosalie-fix

- src/Provider/HomeProvider.php
- templates/homeV2/sections/our-solutions-section.html.twig
- templates/homeV2/templates/product-is-template.html.twig
[Ticket](https://trello.com/c/6UDlcLX0/4299-3-ajout-logo-qualiopi)
> Ajout logo Qualiopi

- templates/homeV2/pages/contact.html.twig
- templates/homeV2/sections/digital_cares_section.html.twig
- templates/homeV2/sections/page-rp-hero-section.html.twig
[Ticket 1](https://trello.com/c/PHZ877Ns/4352-1-ajouter-la-bretagne-sur-la-partie-contactez-nos-antennes-de-la-page-contactez-nous) + [Ticket 2](https://trello.com/c/9qojxvys/4354-05-fix-bouton-de-connexion-rp-bouton-catalogue-formation-des-acc-num%C3%A9riques)
> Ajouter la Bretagne sur la partie Contactez nos antennes + Fix boutons

- src/Entity/User.php
- src/EventSubscriber/UserCreationSubscriber.php
- tests/v2/Listener/UserCreationListenerTest.php
[Ticket](https://trello.com/c/ALEK5V5Y/4308-2-rosalie-v%C3%A9rification-si-le-sms-est-bien-envoy%C3%A9)
> [Main] Rosalie vérification si le SMS est bien envoyé 

- templates/homeV2/pages/contact.html.twig
- templates/homeV2/sections/digital_cares_section.html.twig
- templates/homeV2/sections/page-rp-hero-section.html.twig
[Ticket 1](https://trello.com/c/PHZ877Ns/4352-1-ajouter-la-bretagne-sur-la-partie-contactez-nos-antennes-de-la-page-contactez-nous) + [Ticket 2](https://trello.com/c/9qojxvys/4354-05-fix-bouton-de-connexion-rp-bouton-catalogue-formation-des-acc-num%C3%A9riques)
> [Main] Ajouter la Bretagne sur la partie Contactez nos antennes + Fix boutons

- templates/v2/pro/create/index.html.twig
[Ticket](https://trello.com/c/6nUFDy8V/4333-05-page-https-reconnectfr-pro-create-home-modifier-licone-dajout-dun-utilisateur)
> Page https://reconnect.fr/pro/create/home modifier l'icone d'ajout d'un utilisateur

- src/Admin/BeneficiaireCentreAdmin.php
[Ticket](https://trello.com/c/oyhNbczR/4358-1-je-ne-peux-pas-affilier-de-centre-%C3%A0-un-b%C3%A9n%C3%A9ficiaire-lors-de-la-cr%C3%A9ation)
> Je ne peux pas affilier de Centre à un bénéficiaire lors de la création

- src/Admin/BeneficiaireCentreAdmin.php
[Ticket](https://trello.com/c/oyhNbczR/4358-1-je-ne-peux-pas-affilier-de-centre-%C3%A0-un-b%C3%A9n%C3%A9ficiaire-lors-de-la-cr%C3%A9ation)
> [Main] Je ne peux pas affilier de Centre à un bénéficiaire lors de la création

- src/Provider/HomeProvider.php
- templates/homeV2/sections/our-solutions-section.html.twig
- templates/homeV2/templates/product-is-template.html.twig
[Ticket](https://trello.com/c/CaSNpqHT/4385-2-modifications-qualiopi)
> Modifications Qualiopi

- src/Provider/HomeProvider.php
- templates/homeV2/sections/our-solutions-section.html.twig
- templates/homeV2/templates/product-is-template.html.twig
[Ticket](https://trello.com/c/CaSNpqHT/4385-2-modifications-qualiopi)
> [Main] Modifications Qualiopi

- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/vjFkUerA/4320-5-liaison-cfn-rosalie-%C3%A0-lajout-dun-num%C3%A9ro-si-siao)
> Liaison CFN - Rosalie à l'ajout d'un numéro SI-SIAO

- assets/controllers/ajax_list_filter_controller.js
[Ticket](https://trello.com/c/0umj0OdI/4382-3-listes-probl%C3%A8me-quand-jappuie-sur-entr%C3%A9e-lors-de-la-recherche)
> Listes - Problème quand j'appuie sur Entrée lors de la recherche

- assets/css/appV2/pagination.scss
[Ticket](https://trello.com/c/TZaraJNL/4373-1-little-ux-probl%C3%A8me-sur-la-page-des-documents)
>  Little UX problème sur la page des documents

- assets/css/appV2/pagination.scss
[Ticket](https://trello.com/c/TZaraJNL/4373-1-little-ux-probl%C3%A8me-sur-la-page-des-documents)
> [Main] Little UX problème sur la page des documents

- src/Repository/BeneficiaireRepository.php
- src/Repository/MembreRepository.php
- src/Repository/UserRepository.php
[Ticket](https://trello.com/c/k35UXWLI/4381-3-recherche-de-b%C3%A9n%C3%A9ficiaire-pro-la-recherche-ne-marche-pas-si-jentre-plusieurs-mots)
> [Main] Recherche de Bénéficiaire/pro - La recherche ne marche pas si j'entre plusieurs mots

- assets/controllers/ajax_list_filter_controller.js
[Ticket](https://trello.com/c/0umj0OdI/4382-3-listes-probl%C3%A8me-quand-jappuie-sur-entr%C3%A9e-lors-de-la-recherche)
> [Main] Listes - Problème quand j'appuie sur Entrée lors de la recherche

- templates/homeV2/templates/contact-us-template.html.twig
[Ticket](https://trello.com/c/AZg4nR5l/4448-0-changer-le-lien-vers-la-newsletter-0)
> :recycle: [Brevo] Changed newlsetter form url

- src/EventSubscriber/UserCreationSubscriber.php
[Ticket](https://trello.com/c/1UKOQUav/4466-05-mail-doublon-b%C3%A9n%C3%A9ficiaire-d%C3%A9sactiver-sur-preprod-cfn)
> Mail doublon bénéficiaire - Désactiver sur preprod CFN 

- assets/controllers/tooltip_controller.js
- assets/css/appV2/theme.scss
- templates/v2/common/_button_with_loader.html.twig
- templates/v2/common/_card.html.twig
- templates/v2/pro/list/_update_permission_button.html.twig
- templates/v2/user_creation/components/_permissions_checkbox.html.twig
- templates/v2/vault/components/_toggle_visibility_button.html.twig
[Ticket](https://trello.com/c/pnVTcwIE/4445-2-sur-le-cfn-web-je-nai-plus-le-tooltip-sur-lacc%C3%A8s-priv%C3%A9-ou-partag%C3%A9-dun-document)
> [Main] Je n'ai plus le tooltip sur l'accès privé ou partagé d'un document

- src/EventSubscriber/UserCreationSubscriber.php
[Ticket](https://trello.com/c/1UKOQUav/4466-05-mail-doublon-b%C3%A9n%C3%A9ficiaire-d%C3%A9sactiver-sur-preprod-cfn)
> [Main] Mail doublon bénéficiaire - Désactiver sur preprod CFN

- templates/homeV2/templates/contact-us-template.html.twig
[Ticket](https://trello.com/c/hP6shCGP/4428-5-modifier-le-template-de-base-du-mail-de-double-opt-in)
>  Modifier le template de base du mail de double opt-in

- src/ControllerV2/RosalieInteroperabilityController.php
- src/Repository/ClientBeneficiaireRepository.php
- src/ServiceV2/RosalieService.php
- tests/v2/Service/RosalieServiceTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/X6ArKYNr/4462-2-pr%C3%A9venir-les-erreurs-500-%C3%A0-la-cr%C3%A9ation-de-lien-rosalie-avec-un-num-d%C3%A9j%C3%A0-existant)
> Prévenir les erreurs 500 à la création de lien Rosalie avec un num déjà existant

- config/preprod/deploy.php
[Ticket](https://trello.com/c/viofw5pm/4264-2-enqu%C3%AAte-2h-opcache-preprod-cfn-v%C3%A9rifier-bon-fonctionnement-du-flush-apr%C3%A8s-le-retour-doceanet)
> :rocket: [Preprod/deploy] Reset opcache on deploy

- config/preprod/deploy.php
[Ticket](https://trello.com/c/viofw5pm/4264-2-enqu%C3%AAte-2h-opcache-preprod-cfn-v%C3%A9rifier-bon-fonctionnement-du-flush-apr%C3%A8s-le-retour-doceanet)
> [Main] :rocket: [Preprod/deploy] Reset opcache on deploy

- tests/v2/Listener/UserCreationListenerTest.php
[Ticket](https://trello.com/c/aiRYmMRM/4378-1-enqu%C3%AAte-1h-test-qui-%C3%A9choue-de-mani%C3%A8re-r%C3%A9guli%C3%A8re)
>  Test qui échoue de manière régulière (username)

- tests/v2/Listener/UserCreationListenerTest.php
[Ticket](https://trello.com/c/aiRYmMRM/4378-1-enqu%C3%AAte-1h-test-qui-%C3%A9choue-de-mani%C3%A8re-r%C3%A9guli%C3%A8re)
> [Main] Test qui échoue de manière régulière (username)

- config/services.yaml
- crontab
- src/Command/Scheduled/CheckDiskCapacityCommand.php
- src/Command/Scheduled/SendRemindersSmsCommand.php
[Ticket](https://trello.com/c/AFHnMzuG/4454-5-enqu%C3%AAte-5h-faire-le-check-des-capacit%C3%A9s-serveurs-automatiquement)
> Faire le check des capacités serveurs automatiquement

- src/ControllerV2/ResetPasswordController.php
- src/ControllerV2/SharedDocumentController.php
- src/Service/LanguageService.php
- src/ServiceV2/Mailer/MailerService.php
[Ticket](https://trello.com/c/mwPZyydx/4486-3-nouveau-retours-mailer)
> Nouveau retours mailer -> vers brevo new mails

- src/ControllerV2/ResetPasswordController.php
- src/ControllerV2/SharedDocumentController.php
- src/Service/LanguageService.php
- src/ServiceV2/Mailer/MailerService.php
[Ticket](https://trello.com/c/mwPZyydx/4486-5-nouveau-retours-mailer)
> Nouveaux retours Mailer

- src/ControllerV2/RosalieInteroperabilityController.php
- src/Repository/ClientBeneficiaireRepository.php
- src/ServiceV2/RosalieService.php
- tests/v2/Service/RosalieServiceTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/X6ArKYNr/4462-2-pr%C3%A9venir-les-erreurs-500-%C3%A0-la-cr%C3%A9ation-de-lien-rosalie-avec-un-num-d%C3%A9j%C3%A0-existant)
> [Main] Prévenir les erreurs 500 à la création de lien Rosalie avec un num déjà existant

- crontab
- src/Command/Scheduled/CheckAppLogsCommand.php
[Ticket](https://trello.com/c/lHfbcDvI/4413-3-v%C3%A9rification-automatique-le-dimanche-que-les-logs-sont-bien-enregistr%C3%A9s)
> Vérification automatique le dimanche que les logs sont bien enregistrés

- src/ControllerV2/BeneficiaryAffiliationController.php
[Ticket](https://trello.com/c/5GqGwzh5/4528-05-en-tant-que-pro-sans-permission-de-gestion-des-b%C3%A9n%C3%A9ficiaires-jai-une-403-lorsque-je-valide-laffiliation-dun-b%C3%A9n%C3%A9ficiaire)
> En tant que pro sans permission de gestion des bénéficiaires, j'ai une 403 lorsque je valide l'affiliation d'un bénéficiaire

- src/ControllerV2/BeneficiaryAffiliationController.php
[Ticket](https://trello.com/c/5GqGwzh5/4528-05-en-tant-que-pro-sans-permission-de-gestion-des-b%C3%A9n%C3%A9ficiaires-jai-une-403-lorsque-je-valide-laffiliation-dun-b%C3%A9n%C3%A9ficiaire)
> [Main] En tant que pro sans permission de gestion des bénéficiaires, j'ai une 403 lorsque je valide l'affiliation d'un bénéficiaire

- crontab
- src/Command/Scheduled/CheckAppLogsCommand.php
[Ticket](https://trello.com/c/lHfbcDvI/4413-3-v%C3%A9rification-automatique-le-dimanche-que-les-logs-sont-bien-enregistr%C3%A9s)
> [Main] Vérification automatique le dimanche que les logs sont bien enregistrés

- Makefile
- src/ControllerV2/RosalieInteroperabilityController.php
- templates/v2/user_creation/beneficiary/_rosalie_row.html.twig
- templates/v2/user_creation/beneficiary/_step_5.html.twig
- translations/messages.fr.yml
[Ticket](https://trello.com/c/GAWYDgcf/4500-5-si-je-suis-user-rosalie-sur-la-page-r%C3%A9cap-des-informations-je-sais-si-le-cfn-en-cr%C3%A9ation-est-li%C3%A9-%C3%A0-rosalie-et-je-peux-relancer)
> Si je suis user Rosalie, sur la page récap des informations je sais si le CFN en création est lié à Rosalie

- src/ControllerV2/RosalieInteroperabilityController.php
- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
- templates/v2/user_creation/beneficiary/_rosalie_row.html.twig
- tests/v2/Controller/RosalieInteroperabilityController/AddSiSiaoNumberTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/q8gmblp2/4501-4-si-je-suis-user-rosalie-et-que-le-b%C3%A9n%C3%A9f-a-d%C3%A9j%C3%A0-un-num%C3%A9ro-sisiao-en-bdd-lorsque-je-laffilie-%C3%A0-un-centre-le-process-de-liaison-r)
>  Lorsque j'affilie un beneficiaire à un centre, le process de liaison Rosalie s'effectue 

- src/Admin/CentreAdmin.php
[Ticket](https://trello.com/c/vOJLSss4/4504-3-export-des-centres)
> Export des centres

- templates/homeV2/templates/contact-us-template.html.twig
[Ticket](https://trello.com/c/BGkejynO/4341-3-suite-inscription-newsletter)
> [Main] Suite inscription newsletter

- config/packages/admin.yaml
[Ticket](https://trello.com/c/TOQ7luM3/4324-05-renommer-onglet-membres-professionnels)
> (0.5) Renommer onglet Membres -> Professionnels

- src/Controller/UserController.php
[Ticket](https://trello.com/c/LBKLZTyh/4586-05-impossible-de-valider-les-cgs-%C3%A0-la-premi%C3%A8re-connexion)
> Impossible de valider les cgs à la première connexion

- src/Controller/UserController.php
[Ticket](https://trello.com/c/LBKLZTyh/4586-05-impossible-de-valider-les-cgs-%C3%A0-la-premi%C3%A8re-connexion)
> [Main] Impossible de valider les cgs à la première connexion

- config/preprod/deploy.php
- src/Deployer.php
> :rocket: [Deploy/prod] Flush opcache for prod env

- src/Entity/User.php
[Ticket](https://trello.com/c/BIettoi2/4590-2-enqu%C3%AAte-2h-on-ne-peut-pas-acc%C3%A9der-%C3%A0-la-documentation-de-lapi)
> :bug: [API Docs] Fix duplicated group annotation

- src/ControllerV2/UserController.php
- src/ServiceV2/Mailer/MailerService.php
- templates/v2/user/request_personal_account_data.html.twig
- templates/v2/user/settings.html.twig
- tests/v2/Controller/UserController/RequestAccountDataTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/rxCLMjPP/4591-5-etqb-je-peux-effectuer-une-demande-de-r%C3%A9cup%C3%A9ration-de-mes-donn%C3%A9es)
> ETQB, je peux effectuer une demande de récupération de mes données

- src/Controller/Rest/V3/UserController.php
- src/ServiceV2/Mailer/MailerService.php
- tests/v2/Controller/UserController/RequestAccountDataTest.php
[Ticket](https://trello.com/c/khh341jo/4636-2-api-exposer-une-route-pour-la-demande-de-r%C3%A9cup%C3%A9ration-des-donn%C3%A9es-du-compte-par-mail)
> Exposer une route pour la demande de récupération des données du compte par mail

- src/Controller/Rest/V3/UserController.php
- src/ServiceV2/Mailer/MailerService.php
- tests/v2/Controller/UserController/RequestAccountDataTest.php
[Ticket](https://trello.com/c/khh341jo/4636-2-exposer-une-route-pour-la-demande-de-r%C3%A9cup%C3%A9ration-de-donn%C3%A9es-par-mail)
> Exposer une route pour la demande de récupération de données par mail -> vers feature/get-account-data

- config/packages/security.yaml
- tests/v2/Listener/UserCreationListenerTest.php
[Ticket](https://trello.com/c/gLTJ0mSc/4537-3-cr%C3%A9er-un-role-de-superadmin-permettant-de-cr%C3%A9er-des-users-au-r%C3%B4le-admin-3)
> :sparkles: [Admin] Restrict admin management access to superadmins

- src/ControllerV2/BeneficiaryAffiliationController.php
[Ticket](https://trello.com/c/4w8ieKxY/4645-etqp-quand-jaffilie-un-b%C3%A9n%C3%A9ficiaire-d%C3%A9j%C3%A0-existant-via-la-question-secr%C3%A8te-et-que-je-clique-sur-confirmer-apr%C3%A8s-lavoir-affili%C3%A9-je)
> Erreur 500 à l'affiliation

- src/Admin/DossierAdmin.php
[Ticket](https://trello.com/c/6i5eZ7vt/4632-05-etqa-etqsa-sur-la-page-d%C3%A9dition-dun-dossier-je-ne-peux-pas-modifier-le-nom-de-celui-ci)
> ETQA, ETQSA, Sur la page d'édition d'un dossier, je ne peux pas modifier le nom de celui-ci

- src/Admin/DossierAdmin.php
[Ticket](https://trello.com/c/6i5eZ7vt/4632-05-etqa-etqsa-sur-la-page-d%C3%A9dition-dun-dossier-je-ne-peux-pas-modifier-le-nom-de-celui-ci)
>  [Main] ETQA, ETQSA, Sur la page d'édition d'un dossier, je ne peux pas modifier le nom de celui-ci

- src/Admin/MembreAdmin.php
> ✨ [MemberAdmin] Add cgs acceptance date column on list view

- config/packages/admin.yaml
[Ticket](https://trello.com/c/TOQ7luM3/4324-05-renommer-onglet-membres-professionnels)
> [Main] :lipstick: [Admin] Renamed Membres into Professionnels

- src/Admin/CentreAdmin.php
[Ticket](https://trello.com/c/vOJLSss4/4504-3-export-des-centres)
> [Main] Export des centres

- config/packages/admin.yaml
- config/packages/security.yaml
- config/packages/sonata_admin.yaml
- src/Admin/AdminUserAdmin.php
- src/Admin/UserSimpleAdmin.php
- src/Controller/SecurityController.php
- src/Entity/User.php
- src/ManagerV2/UserManager.php
- tests/v2/Listener/UserCreationListenerTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/gLTJ0mSc/4537-3-cr%C3%A9er-un-role-de-superadmin-permettant-de-cr%C3%A9er-des-users-au-r%C3%B4le-admin)
> [Main] Créer un role de SUPER_ADMIN permettant de créer des users au rôle admin

- config/doctrine/User.orm.yml
- src/Admin/BeneficiaireAdmin.php
- src/Controller/Rest/V3/UserController.php
- src/ControllerV2/UserController.php
- src/Entity/User.php
- src/Migrations/Version20240129152854.php
- templates/v2/user/request_personal_account_data.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/s1KTJXCe/4618-5-etqb-je-ne-peux-effectuer-quune-demande-de-r%C3%A9cup%C3%A9ration-de-mes-donn%C3%A9es)
> ETQB je ne peux effectuer qu'une demande de récupération de mes données 

- assets/controllers/helpers/password_strength_helper.js
- config/validator/user.yml
- tests/v2/Controller/ProController/CreateTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/KGnpWwhT/4663-mise-%C3%A0-jour-politique-mot-de-passe-professionnel)
> Mise à jour politique mot de passe professionnel

- config/packages/twig.yaml
- src/Controller/Rest/DocumentRestV2Controller.php
- src/ControllerV2/BeneficiaryPersonalDataController.php
- src/ControllerV2/MemberBeneficiaryController.php
- src/EventSubscriber/BeneficiaryConsultationSubscriber.php
- src/EventV2/BeneficiaryConsultationEvent.php
- src/ManagerV2/MemberBeneficiaryManager.php
- templates/v2/vault/list_container_layout.html.twig
- tests/v1/Controller/Rest/BeneficiaryConsultationTest.php
- tests/v2/Controller/BeneficiaryConsultation/BeneficiaryConsultationTest.php
[Ticket](https://trello.com/c/ph7dXqdc/4650-3-consultationb%C3%A9n%C3%A9ficiaire)
> ConsultationBénéficiaire

- assets/controllers/helpers/PasswordHelper.js
- assets/controllers/password_strength_controller.js
- src/ControllerV2/GdprController.php
- src/ControllerV2/ResetPasswordController.php
- src/ControllerV2/UserController.php
- src/Entity/User.php
- src/FormV2/ChangePasswordFormType.php
- src/FormV2/ResetPassword/BeneficiaryRequest/ResetPasswordSecretAnswerType.php
- src/FormV2/ResetPassword/BeneficiaryRequest/ResetPasswordSmsFormType.php
- src/Security/Authenticator.php
- src/ServiceV2/Helper/PasswordHelper.php
- src/Validator/Constraints/PasswordCriteria.php
- src/Validator/Constraints/PasswordCriteriaValidator.php
- templates/v2/user/strong_password/_password_strength_widget.html.twig
- templates/v2/user/strong_password/_strong_password_row.html.twig
- tests/v2/Controller/BeneficiaryCreationController/BeneficiaryCreationStep2Test.php
- tests/v2/Controller/BeneficiaryResetPasswordController/SecretAnswerTest.php
- tests/v2/Controller/GdprController/ImprovePasswordTest.php
- tests/v2/Controller/GdprController/UpdatePasswordTest.php
- tests/v2/Controller/ProController/CreateTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
> Nouvel update des règles métier password -> vers feature/professionnals-password-length

- src/EventSubscriber/AbstractWebUserSubscriber.php
- src/Manager/SMSManager.php
> :bug: [SMSManager] Fix error on sprintf

- config/validator/user.yml
- src/Admin/BeneficiaireAdmin.php
- src/Admin/MembreAdmin.php
> :bug: [Admin] Password update is no longer required to update user

- src/Admin/BeneficiaireAdmin.php
> :bug: [Admin] Fix 500 at benef creation

- config/doctrine/User.orm.yml
- src/Admin/BeneficiaireAdmin.php
- src/Controller/Rest/V3/UserController.php
- src/ControllerV2/UserController.php
- src/Entity/User.php
- src/Migrations/Version20240129152854.php
- templates/v2/user/request_personal_account_data.html.twig
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/s1KTJXCe/4618-5-etqb-je-ne-peux-effectuer-quune-demande-de-r%C3%A9cup%C3%A9ration-de-mes-donn%C3%A9es)
>  [Main] ETQB je ne peux effectuer qu'une demande de récupération de mes données

- config/packages/twig.yaml
- src/Controller/Rest/DocumentRestV2Controller.php
- src/ControllerV2/BeneficiaryPersonalDataController.php
- src/ControllerV2/MemberBeneficiaryController.php
- src/EventSubscriber/BeneficiaryConsultationSubscriber.php
- src/EventV2/BeneficiaryConsultationEvent.php
- src/ManagerV2/MemberBeneficiaryManager.php
- templates/v2/vault/list_container_layout.html.twig
- tests/v1/Controller/Rest/BeneficiaryConsultationTest.php
- tests/v2/Controller/BeneficiaryConsultation/BeneficiaryConsultationTest.php
[Ticket](https://trello.com/c/ph7dXqdc/4650-3-consultationb%C3%A9n%C3%A9ficiaire)
> [Main] ConsultationBénéficiaire

- src/ControllerV2/UserController.php
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/DataFixtures/v2/MemberFixture.php
- src/EventSubscriber/UserCreationSubscriber.php
- src/FormV2/FirstVisitType.php
- src/Validator/Constraints/AcceptCGSValidator.php
- tests/Factory/UserFactory.php
- tests/v2/Controller/BeneficiaryCreationController/BeneficiaryCreationStep2Test.php
- tests/v2/Controller/ProController/CreateTest.php
- tests/v2/Controller/SecurityController/MfaTest.php
- tests/v2/Controller/UserController/CgsTest.php
- tests/v2/Controller/UserController/SettingsTest.php
[Ticket](https://trello.com/c/1VpmyTln/4693-3-visuel-2fa-b%C3%A9n%C3%A9ficiaires-professionnels-4)
> Visuel 2FA - Bénéficiaires & Professionnels - Retours validation + préparation tests

- src/Controller/SecurityController.php
- tests/v2/Controller/SecurityController/MfaTest.php
> :recycle: [2FA] Refacto test to make it resilient

- src/Form/Type/UserType.php
- src/FormV2/ChangePasswordFormType.php
- src/FormV2/Field/PasswordField.php
- src/FormV2/UserCreation/CreateBeneficiaryType.php
- src/FormV2/UserCreation/CreateUserType.php
- templates/v2/user_creation/components/_password_card.html.twig
[Ticket](https://trello.com/c/xTV5G92o/4731-2-etqp-%C3%A0-la-cr%C3%A9ation-dun-b%C3%A9n%C3%A9ficiaire-les-chips-de-validation-du-password-doivent-fonctionner)
> [Main] ETQP à la création d'un bénéficiaire, les chips de validation du password doivent fonctionner

- translations/messages.it.yml
> :globe_with_meridians: [Trans] Fix it trans

- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
> :lipstick: [Affiliation] Changed edit icon color

- src/Command/DataFixer/FixRPExternalLinkCommand.php
- src/Entity/Beneficiaire.php
- src/Entity/Client.php
- src/Repository/BeneficiaireRepository.php
[Ticket](https://trello.com/c/WMwcDWLp/4652-5-enqu%C3%AAte-bug-thomas)
> Bug liens vers RP rompus

- src/Command/DataFixer/FixRPExternalLinkCommand.php
[Ticket](https://trello.com/c/ycMzGJLC/4746-2-bug-thomas-suite)
> Suite bug Thomas

- templates/v2/vault/event/_card.html.twig
- templates/v2/vault/event/detail.html.twig
[Ticket](https://trello.com/c/OrJGII1W/4744-5-etqu-quand-jajoute-un-%C3%A9v%C3%A8nement-lheure-devrait-senregistrer-safficher-%C3%A0-lheure-du-fuseau-horaire-du-lieu)
>  ETQU, Quand j'ajoute un évènement l'heure devrait s'enregistrer & s'afficher à l'heure du fuseau horaire du lieu

- templates/v2/vault/event/_card.html.twig
- templates/v2/vault/event/_detail_information.html.twig
[Ticket](https://trello.com/c/OrJGII1W/4744-5-etqu-quand-jajoute-un-%C3%A9v%C3%A8nement-lheure-devrait-senregistrer-safficher-%C3%A0-lheure-du-fuseau-horaire-du-lieu)
> ETQU, Quand j'ajoute un évènement l'heure devrait s'enregistrer & s'afficher à l'heure du fuseau horaire du lieu --> Rappels

- src/Command/DataFixer/FixRPExternalLinkCommand.php
[Ticket](https://trello.com/c/ZdDuqjvG/4754-5-bug-champs-historisés-différents-fiche-suivi-exports)
> :recycle: [FixRPLink] Updated Command

- .env
- config/doctrine/Centre.orm.yml
- config/doctrine/Region.orm.yml
- config/packages/admin.yaml
- config/packages/sonata_admin.yaml
- config/services.yaml
- src/Admin/CentreAdmin.php
- src/Admin/RegionAdmin.php
- src/Command/DataMigration/MigrateRegionsToTableCommand.php
- src/DataFixtures/v2/RegionFixture.php
- src/Entity/Centre.php
- src/Entity/Region.php
- src/Migrations/Version20240228153218.php
- src/Repository/CentreRepository.php
- src/Repository/RegionRepository.php
- src/ServiceV2/Mailer/Email/DuplicatedUsernameEmail.php
- src/ServiceV2/Mailer/Email/LocalizedTemplatedEmail.php
- src/ServiceV2/Mailer/MailerService.php
- templates/v2/email/duplicated_user.html.twig
- tests/Factory/RegionFactory.php
- tests/v2/Entity/AbstractEntityTest.php
- tests/v2/Entity/RegionTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/ANNWOIV8/4621-8-mail-doublon-b%C3%A9n%C3%A9ficiaire)
> Mail doublon bénéficiaire

- translations/messages.en.yml
- translations/messages.fr.yml
- translations/security/security.en.yml
[Ticket](https://trello.com/c/ocbFwbRR/4734-2-incoh%C3%A9rences-langues)
> [Main]  Incohérences langues

- src/Admin/ContactAdmin.php
- src/Admin/EvenementAdmin.php
[Ticket](https://trello.com/c/bfRYYeV2/4633-2-lorsque-je-clique-sur-lid-dun-%C3%A9v%C3%A9nement-ou-dun-contact-jarrive-sur-une-page-derreur)
> Lorsque je clique sur l'ID d'un événement ou d'un contact, j'arrive sur une page d'erreur

- src/EventSubscriber/UserCreationSubscriber.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/ANNWOIV8/4621-8-mail-doublon-b%C3%A9n%C3%A9ficiaire-13)
> :bug: [Mail] Fixed mail subject translation

- .env
- config/doctrine/Centre.orm.yml
- config/doctrine/Region.orm.yml
- config/packages/admin.yaml
- config/packages/sonata_admin.yaml
- config/services.yaml
- src/Admin/CentreAdmin.php
- src/Admin/RegionAdmin.php
- src/Command/DataMigration/MigrateRegionsToTableCommand.php
- src/DataFixtures/v2/RegionFixture.php
- src/Entity/Centre.php
- src/Entity/Region.php
- src/EventSubscriber/UserCreationSubscriber.php
- src/Migrations/Version20240228153218.php
- src/Repository/CentreRepository.php
- src/Repository/RegionRepository.php
- src/ServiceV2/Mailer/Email/DuplicatedUsernameEmail.php
- src/ServiceV2/Mailer/Email/LocalizedTemplatedEmail.php
- src/ServiceV2/Mailer/MailerService.php
- templates/v2/email/duplicated_user.html.twig
- tests/Factory/RegionFactory.php
- tests/v2/Entity/AbstractEntityTest.php
- tests/v2/Entity/RegionTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/ANNWOIV8/4621-8-mail-doublon-b%C3%A9n%C3%A9ficiaire)
> [Main] Mail doublon bénéficiaire

- translations/messages.en.yml
> :bug: [Trans] Fix en trad

- src/Exception/NoMoreSpaceException.php
- templates/v2/user/disaffiliation/disaffiliate.html.twig
[Ticket](https://trello.com/c/Zf6xlhjv/4644-1-etqp-quand-je-d%C3%A9saffilie-un-b%C3%A9n%C3%A9ficiaire-dun-relai-je-peux-cliquer-sur-un-bouton-terminer-qui-me-ram%C3%A8ne-%C3%A0-la-liste-des-benefs)
> ETQP, Quand je désaffilie un bénéficiaire d'un relai, je peux cliquer sur un bouton "Terminer" qui me ramène à la liste des benefs actualisée

- src/Admin/BeneficiaireAdmin.php
- src/Entity/Beneficiaire.php
[Ticket](https://trello.com/c/gKbAZ8Ti/4730-3-etqa-lorsque-jexporte-la-liste-des-b%C3%A9n%C3%A9ficiaires-jai-le-nbre-de-contacts-nbre-%C3%A9v%C3%A9nements-et-nbre-notes)
> ETQA, lorsque j'exporte la liste des bénéficiaires, j'ai le nbre de contacts, nbre événements et nbre notes (+ retrait nom prénom)

- src/Admin/BeneficiaireAdmin.php
- src/Admin/ContactAdmin.php
- src/Admin/DocumentAdmin.php
- src/Admin/DossierAdmin.php
- src/Admin/EvenementAdmin.php
- src/Admin/MembreAdmin.php
- src/Admin/NoteAdmin.php
[Ticket](https://trello.com/c/vkMtbqTC/4788-1-bug-filtres-r%C3%A9gions)
> [Main] Bug filtres régions

- src/Exception/NoMoreSpaceException.php
- templates/v2/user/disaffiliation/disaffiliate.html.twig
[Ticket](https://trello.com/c/Zf6xlhjv/4644-1-etqp-quand-je-d%C3%A9saffilie-un-b%C3%A9n%C3%A9ficiaire-dun-relai-je-peux-cliquer-sur-un-bouton-terminer-qui-me-ram%C3%A8ne-%C3%A0-la-liste-des-benefs)
> [Main] ETQP, Quand je désaffilie un bénéficiaire d'un relai, je peux cliquer sur un bouton "Terminer" qui me ramène à la liste des benefs actualisée

- config/packages/admin.yaml
- src/Admin/MembreAdminController.php
[Ticket](https://trello.com/c/AAqT5iRg/4596-5-enqu%C3%AAte-5h-etqsa-je-peux-supprimer-un-membre-non-test-sil-est-affili%C3%A9-%C3%A0-aucun-centre)
[Ticket](https://trello.com/c/lSLsjkMQ/4595-0-etqa-je-peux-supprimer-un-membre-test-sil-nest-affili%C3%A9-%C3%A0-aucun-centre)
[Ticket](https://trello.com/c/Uy6HSwFb/4574-0-etqa-je-ne-devrais-pas-pouvoir-supprimer-des-membres-non-test)
> ETQSA, je peux supprimer un membre non test s'il est affilié à aucun centre

- src/Admin/MembreAdminController.php
> :recycle: [MembreAdminController] Update flash messages

- config/packages/admin.yaml
- src/Admin/MembreAdminController.php
[Ticket](https://trello.com/c/AAqT5iRg/4596-5-enqu%C3%AAte-5h-etqsa-je-peux-supprimer-un-membre-non-test-sil-est-affili%C3%A9-%C3%A0-aucun-centre)
[Ticket](https://trello.com/c/lSLsjkMQ/4595-0-etqa-je-peux-supprimer-un-membre-test-sil-nest-affili%C3%A9-%C3%A0-aucun-centre)
[Ticket](https://trello.com/c/Uy6HSwFb/4574-0-etqa-je-ne-devrais-pas-pouvoir-supprimer-des-membres-non-test)
> [Main] ETQSA, je peux supprimer un membre non test s'il est affilié à aucun centre

- src/Form/Model/ExportModel.php
- src/Form/Type/ExportType.php
- src/Service/ExportService.php
[Ticket](https://trello.com/c/56ZVoyTV/4809-bug-export-de-stats)
> Bug export de stats

- Makefile
- src/Command/DataFixer/FixRPExternalLinkCommand.php
- src/DataFixtures/ORM/BeneficiaireFixture.php
- src/DataFixtures/ORM/ClientFixtures.php
- src/DataFixtures/ORM/GestionnaireAssociationCentreFixture.php
- src/DataFixtures/ORM/MembreFixture.php
- src/DataFixtures/v2/ClientFixture.php
- src/Entity/Beneficiaire.php
- src/Entity/Client.php
- src/Repository/BeneficiaireCentreRepository.php
- src/Repository/BeneficiaireRepository.php
- src/Repository/ClientBeneficiaireRepository.php
- tests/v1/Controller/Rest/BeneficiaireRestV2ControllerTest.php
[Ticket](https://trello.com/c/kDOKoBSp/4741-enquête-3h-3-migration-axel-rp)
> Migration Axel - RP

- assets/controllers/ajax_list_filter_controller.js
- config/doctrine/Rappel.orm.yml
- src/ControllerV2/BeneficiaryPersonalDataController.php
- src/Entity/Evenement.php
- src/Entity/Rappel.php
- src/Form/Type/RappelType.php
- src/FormV2/EventType.php
- src/FormV2/ReminderType.php
- src/ListenerV2/TimezoneListener.php
- src/ManagerV2/EventManager.php
- src/Migrations/Version20240325105001.php
- src/Repository/EvenementRepository.php
- src/Validator/Constraints/Evenement/EntityValidator.php
- templates/components/event_form.html.twig
- templates/v2/common/_link_button.html.twig
- templates/v2/vault/event/index.html.twig
- tests/v2/Controller/EventController/CreateTest.php
- translations/messages.en.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/OrJGII1W/4744-5-etqu-quand-jajoute-un-%C3%A9v%C3%A8nement-lheure-devrait-senregistrer-safficher-%C3%A0-lheure-du-fuseau-horaire-du-lieu-5)
> ETQU, Quand j'ajoute un évènement l'heure devrait s'enregistrer & s'afficher à l'heure du fuseau horaire du lieu

- Makefile
- src/Command/DataFixer/FixRPExternalLinkCommand.php
- src/DataFixtures/ORM/BeneficiaireFixture.php
- src/DataFixtures/ORM/ClientFixtures.php
- src/DataFixtures/ORM/GestionnaireAssociationCentreFixture.php
- src/DataFixtures/ORM/MembreFixture.php
- src/DataFixtures/v2/ClientFixture.php
- src/Entity/Beneficiaire.php
- src/Entity/Client.php
- src/Repository/BeneficiaireCentreRepository.php
- src/Repository/BeneficiaireRepository.php
- src/Repository/ClientBeneficiaireRepository.php
- tests/v1/Controller/Rest/BeneficiaireRestV2ControllerTest.php
[Ticket](https://trello.com/c/kDOKoBSp/4741-enquête-3h-3-migration-axel-rp)
> [Main] Migration Axel - RP

- src/Entity/Beneficiaire.php
> [API v3] Restore GetCollection endpoint

- deploy.php
> :recycle: [Deploy] Update tasks order

- config/doctrine/Rappel.orm.yml
- src/Entity/Evenement.php
- src/Entity/Rappel.php
- src/Form/Type/RappelType.php
- src/FormV2/EventType.php
- src/FormV2/ReminderType.php
- src/ListenerV2/TimezoneListener.php
- src/ManagerV2/EventManager.php
- src/Migrations/Version20240325105001.php
- src/Validator/Constraints/Evenement/EntityValidator.php
- templates/components/event_form.html.twig
- tests/v2/Controller/EventController/CreateTest.php
[Ticket](https://trello.com/c/OrJGII1W/4744-5-etqu-quand-jajoute-un-%C3%A9v%C3%A8nement-lheure-devrait-senregistrer-safficher-%C3%A0-lheure-du-fuseau-horaire-du-lieu)
> (5) ETQU, Quand j'ajoute un évènement l'heure devrait s'enregistrer & s'afficher à l'heure du fuseau horaire du lieu - SUITE

- src/Entity/Rappel.php
- src/Validator/Constraints/Evenement/Entity.php
- src/Validator/Constraints/Evenement/EntityValidator.php
- src/Validator/Constraints/Rappel/Entity.php
- src/Validator/Constraints/Rappel/EntityValidator.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/6Lh6hmbL/4766-enqu%C3%AAte-5h-5-etqu-quand-jajoute-un-rappel-celui-ci-devrait-%C3%AAtre-coh%C3%A9rent-avec-mon-fuseau-horaire)
> [Enquête 5h] (5) ETQU, quand j'ajoute un rappel celui-ci devrait être cohérent avec mon fuseau horaire

- src/Entity/Rappel.php
- src/Validator/Constraints/Evenement/Entity.php
- src/Validator/Constraints/Evenement/EntityValidator.php
- src/Validator/Constraints/Rappel/Entity.php
- src/Validator/Constraints/Rappel/EntityValidator.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/6Lh6hmbL/4766-enqu%C3%AAte-5h-5-etqu-quand-jajoute-un-rappel-celui-ci-devrait-%C3%AAtre-coh%C3%A9rent-avec-mon-fuseau-horaire)
> [Enquête 5h] (5) ETQU, quand j'ajoute un rappel celui-ci devrait être cohérent avec mon fuseau horaire -> vers feature/allow-create-event-past

- config/doctrine/Rappel.orm.yml
- src/Entity/Evenement.php
- src/Entity/Rappel.php
- src/Form/Type/RappelType.php
- src/FormV2/EventType.php
- src/FormV2/ReminderType.php
- src/ListenerV2/TimezoneListener.php
- src/ManagerV2/EventManager.php
- src/Migrations/Version20240325105001.php
- src/Validator/Constraints/Evenement/Entity.php
- src/Validator/Constraints/Evenement/EntityValidator.php
- src/Validator/Constraints/Rappel/Entity.php
- src/Validator/Constraints/Rappel/EntityValidator.php
- templates/components/event_form.html.twig
- tests/v2/Controller/EventController/CreateTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/OrJGII1W/4744-5-etqu-quand-jajoute-un-%C3%A9v%C3%A8nement-lheure-devrait-senregistrer-safficher-%C3%A0-lheure-du-fuseau-horaire-du-lieu-5)
> ETQU, Quand j'ajoute un évènement l'heure devrait s'enregistrer & s'afficher à l'heure du fuseau horaire du lieu - SUITE -> feature/fix-date-timezone

- config/doctrine/Rappel.orm.yml
- src/Entity/Evenement.php
- src/Entity/Rappel.php
- src/Form/Type/RappelType.php
- src/FormV2/EventType.php
- src/FormV2/ReminderType.php
- src/ListenerV2/TimezoneListener.php
- src/ManagerV2/EventManager.php
- src/Migrations/Version20240325105001.php
- src/Repository/EvenementRepository.php
- src/Validator/Constraints/Evenement/Entity.php
- src/Validator/Constraints/Evenement/EntityValidator.php
- src/Validator/Constraints/Rappel/Entity.php
- src/Validator/Constraints/Rappel/EntityValidator.php
- templates/components/event_form.html.twig
- templates/v2/vault/event/_card.html.twig
- templates/v2/vault/event/_detail_information.html.twig
- templates/v2/vault/event/detail.html.twig
- tests/v2/Controller/EventController/CreateTest.php
- translations/messages.fr.yml
[Ticket](https://trello.com/c/OrJGII1W/4744-5-etqu-quand-jajoute-un-%C3%A9v%C3%A8nement-lheure-devrait-senregistrer-safficher-%C3%A0-lheure-du-fuseau-horaire-du-lieu)
> [Main] ETQU, Quand j'ajoute un évènement l'heure devrait s'enregistrer & s'afficher à l'heure du fuseau horaire du lieu

- src/Admin/UserSimpleAdmin.php
- src/Command/DataMigration/MigrateDerniereConnexionAtCommand.php
- src/Entity/User.php
- src/EventSubscriber/Logs/LoginSubscriber.php
- src/ManagerV2/UserManager.php
- src/Security/Authenticator.php
- src/ServiceV2/ActivityLogger.php
- tests/v2/EventSubscriber/LoginSubscriberTest.php
- tests/v2/Service/ActivityLoggerTest.php
[Ticket](https://trello.com/c/0SqRFkzi/4823-5-etqa-sur-la-fiche-dun-user-avec-2fa-je-vois-la-date-de-derni%C3%A8re-connexion-qui-correspond-%C3%A0-la-connexion-apr%C3%A8s-validation-de-la)
> [Main] Feature/update last login

- templates/home/sections/digital_cares_section.html.twig
[Ticket](https://trello.com/c/7r947pDG/4609-2-changer-le-bouton-catalogue-de-formation-pour-que-ce-soit-un-annexe-modifiable-depuis-ladmin-directement)
> Changer le bouton "Catalogue de formation" pour que ce soit un annexe modifiable depuis l'admin directement

- translations/messages.fr.yml
[Ticket](https://trello.com/c/0BeKtZ32/4861-modifier-les-chiffres-de-lacc-num-sur-la-home)
> Modifier les chiffres de l'acc num sur la home

- src/Admin/MembreAdmin.php
[Ticket](https://trello.com/c/GhaGac4W/4860-1-etqa-je-peux-voir-dans-lexport-des-professionnels-ceux-qui-sont-actifs-d%C3%A9sactiv%C3%A9s-d%C3%A9placer-colonne-r%C3%A9gion)
>  ETQA, je peux voir dans l'export des professionnels ceux qui sont actifs/désactivés + déplacer colonne Région

- src/ControllerV2/UserController.php
- templates/v2/user/request_personal_account_data.html.twig
> :bug: [RequestAccountData] Fix already requested use case

- templates/home/sections/digital_cares_section.html.twig
[Ticket](https://trello.com/c/7r947pDG/4609-2-changer-le-bouton-catalogue-de-formation-pour-que-ce-soit-un-annexe-modifiable-depuis-ladmin-directement)
> [Main] Changer le bouton "Catalogue de formation" pour que ce soit un annexe modifiable depuis l'admin directement

- src/Admin/MembreAdmin.php
[Ticket](https://trello.com/c/GhaGac4W/4860-1-etqa-je-peux-voir-dans-lexport-des-professionnels-ceux-qui-sont-actifs-d%C3%A9sactiv%C3%A9s-d%C3%A9placer-colonne-r%C3%A9gion)
> [Main] ETQA, je peux voir dans l'export des professionnels ceux qui sont actifs/désactivés + déplacer colonne Région

- translations/messages.fr.yml
[Ticket](https://trello.com/c/0BeKtZ32/4861-modifier-les-chiffres-de-lacc-num-sur-la-home)
> [Main] Modifier les chiffres de l'acc num sur la home

- templates/v2/user/first_visit/first_visit.html.twig
[Ticket](https://trello.com/c/Nakm6Vc7/4695-2-visuel-page-1ere-connexion-professionnels)
> Visuel page 1ere connexion - Professionnels

- src/Admin/MembreAdmin.php
- src/Entity/Traits/DeactivatableTrait.php
[Ticket](https://trello.com/c/GhaGac4W/4860-1-etqa-je-peux-voir-dans-lexport-des-professionnels-ceux-qui-sont-actifs-d%C3%A9sactiv%C3%A9s-d%C3%A9placer-colonne-r%C3%A9gion-1)
> ETQA, je peux voir dans l'export des professionnels ceux qui sont actifs/désactivés

- config/packages/admin.yaml
- src/Admin/UserSimpleAdmin.php
- src/ControllerV2/UserController.php
- tests/v2/Controller/UserController/ResetMfaRetryCount.php
[Ticket](https://trello.com/c/i91YeO3F/4871-3-mfa-bouton-admin-pour-r%C3%A9initialiser-le-nombre-de-renvois)
> MFA - Bouton admin pour réinitialiser le nombre de renvois

- src/ManagerV2/MemberBeneficiaryManager.php
[Ticket](https://trello.com/c/AEdFwhYw/4888-etqp-lors-de-la-premi%C3%A8re-visite-dun-compte-b%C3%A9n%C3%A9ficiaire-cfn-on-devrait-me-proposer-de-partager-automatiquement-mon-contact)
> ETQP, lors de la première visite d'un compte bénéficiaire CFN, on devrait me proposer de partager automatiquement mon contact

- src/Entity/User.php
[Ticket](https://trello.com/c/fE6kGsLR/4899-bug-quand-ma-langue-par-d%C3%A9faut-est-gb)
> Bug quand ma langue par défaut est GB

- src/Entity/User.php
[Ticket](https://trello.com/c/4PzpnaC0/4868-33-cr%C3%A9%C3%A9-par-centre-pour-les-pros)
> :bug: [Pro] Fix bug when creating pro from admin

- assets/controllers/upload_controller.js
- assets/css/appV2/main.scss
- assets/css/appV2/upload.scss
- src/Entity/Document.php
- src/ManagerV2/DocumentManager.php
- templates/v2/vault/document/index.html.twig
[Ticket](https://trello.com/c/q7VlCvAk/2694-2-3-lors-de-lupload-affichage-formats-de-fichiers-support%C3%A9s)
> Affichage Formats de fichiers supportés

- templates/v2/user/first_visit/first_visit.html.twig
[Ticket](https://trello.com/c/Nakm6Vc7/4695-2-visuel-page-1ere-connexion-professionnels)
> [Main] Visuel page 1ere connexion - Professionnels

- src/ManagerV2/MemberBeneficiaryManager.php
[Ticket](https://trello.com/c/AEdFwhYw/4888-etqp-lors-de-la-premi%C3%A8re-visite-dun-compte-b%C3%A9n%C3%A9ficiaire-cfn-on-devrait-me-proposer-de-partager-automatiquement-mon-contact)
> [Main] ETQP, lors de la première visite d'un compte bénéficiaire CFN, on devrait me proposer de partager automatiquement mon contact

- config/packages/admin.yaml
- src/Admin/UserSimpleAdmin.php
- src/ControllerV2/UserController.php
- tests/v2/Controller/UserController/ResetMfaRetryCount.php
[Ticket](https://trello.com/c/i91YeO3F/4871-3-mfa-bouton-admin-pour-r%C3%A9initialiser-le-nombre-de-renvois)
> [Main] MFA - Bouton admin pour réinitialiser le nombre de renvois

- assets/controllers/upload_controller.js
- assets/css/appV2/main.scss
- assets/css/appV2/upload.scss
- src/Entity/Document.php
- src/ManagerV2/DocumentManager.php
- templates/v2/vault/document/index.html.twig
[Ticket](https://trello.com/c/q7VlCvAk/2694-2-3-lors-de-lupload-affichage-formats-de-fichiers-supportés)
> [Main] Affichage Formats de fichiers supportés

- translations/messages.en.yml
[Ticket](https://trello.com/c/RW1IRq3C/4785-1-maj-trad-reset-password-english)
> New translations messages.fr.yml (English)

- phpunit.xml.dist
- src/Admin/UserSimpleAdmin.php
- src/Command/Scheduled/SendRemindersSmsCommand.php
- src/Command/Test/LogSmsReminderSending.php
- src/Kernel.php
- src/ManagerV2/EventManager.php
- tests/v1/Controller/Rest/BeneficiaireRestV2ControllerTest.php
- tests/v2/API/v3/Event/EventApiV3Test.php
- tests/v2/Controller/EventController/CreateTest.php
[Ticket](https://trello.com/c/CvVsDOzl/4841-3-d%C3%A9finir-une-timezone-par-d%C3%A9faut-dans-le-projet)
> :sparkles: [TIMEZONE] Set default timezone to PARIS

- src/Admin/MembreAdmin.php
- src/EventSubscriber/UserCreationSubscriber.php
- tests/v2/EventSubscriber/UserCreationSubscriberTest.php
[Ticket]([Ticket](https://trello.com/c/4PzpnaC0/4868-3-cr%C3%A9%C3%A9-par-centre-pour-les-pros))
> Créé par (Centre) pour les pros

- translations/security/security.en.yml
[Ticket](https://trello.com/c/h8wxD0ST/4917-1-suite-mfa-dur%C3%A9e-de-validit%C3%A9-du-code-trad-anglais)
> Suite MFA - Durée de validité du code - trad Anglais

- src/Admin/MembreAdmin.php
- src/Entity/User.php
- src/EventSubscriber/UserCreationSubscriber.php
- tests/v2/EventSubscriber/UserCreationSubscriberTest.php
[Ticket](https://trello.com/c/4PzpnaC0/4868-3-cr%C3%A9%C3%A9-par-centre-pour-les-pros)
> [2.50.0] Créé par (Centre) pour les pros

- translations/security/security.en.yml
[Ticket](https://trello.com/c/h8wxD0ST/4917-1-suite-mfa-dur%C3%A9e-de-validit%C3%A9-du-code-trad-anglais)
> [2.50.0] Suite MFA - Durée de validité du code - trad Anglais

- .github/workflows/symfony.yaml
- config/packages/monolog.yaml
- phpunit.xml.dist
- src/Admin/UserSimpleAdmin.php
- src/Command/Scheduled/SendRemindersSmsCommand.php
- src/Command/Test/LogSmsReminderSending.php
- src/Kernel.php
- src/ManagerV2/EventManager.php
- tests/v1/Controller/Rest/BeneficiaireRestV2ControllerTest.php
- tests/v2/API/v3/Event/EventApiV3Test.php
- tests/v2/Controller/EventController/CreateTest.php
[Ticket](https://trello.com/c/CvVsDOzl/4841-3-d%C3%A9finir-une-timezone-par-d%C3%A9faut-dans-le-projet)
> [2.50.0] :sparkles: [TIMEZONE] Set default timezone to PARIS

- src/Controller/Rest/DocumentRestV2Controller.php
- src/Controller/Rest/DossierRestV2Controller.php
- src/Entity/Beneficiaire.php
[Ticket](https://trello.com/c/3wOdsH1A/4992-3-etqp-larborescence-de-dossiers-saffiche-mal-dans-le-vault)
> [2.50.1] :bug: [APIv2/Folder] Fix case for root / nested folders

- deploy.php
> :rocket: [Deploy] Update deploy branch

- deploy.php
> [2.50.1] :rocket: [Deploy] Update deploy branch

- src/Controller/Rest/DocumentRestV2Controller.php
- src/Entity/Beneficiaire.php
- src/ManagerV2/FolderManager.php
> :bug: [API/v2] Fix root folders/docs visibility for beneficiary users

- src/Controller/Rest/DocumentRestV2Controller.php
- src/Controller/Rest/DossierRestV2Controller.php
> :bug: [Api/V2] Fix folders

- src/Domain/Anonymization/Anonymizer/UserFilterAnonymizer.php
- src/Entity/User.php
> :bug: [User] Fix unanonymized users

- src/ControllerV2/AbstractController.php
- src/ControllerV2/BeneficiaryCreationController.php
- src/ControllerV2/BeneficiaryPersonalDataController.php
- src/ControllerV2/GdprController.php
- src/ControllerV2/MemberBeneficiaryController.php
- src/ControllerV2/RelayController.php
- src/ControllerV2/SecurityController.php
- src/ControllerV2/UserController.php
- src/EventSubscriber/CheckAcceptedTermsOfUseSubscriber.php
- src/EventSubscriber/PasswordPolicySubscriber.php
- src/ManagerV2/BeneficiaryAffiliationManager.php
> :art: [PhpStan] Prepare lvl 8

- translations/messages.ar.yml
- translations/messages.de.yml
- translations/messages.en.yml
- translations/messages.es.yml
- translations/messages.fa.yml
- translations/messages.fr.yml
- translations/messages.it.yml
- translations/messages.ps.yml
- translations/messages.ru.yml
> L10n -> dev

- templates/home/sections/who-we-are-section.html.twig
[Ticket](https://trello.com/c/SXlmiNd2/4994-3-ajout-rapport-dactivit%C3%A9-sur-le-site)
> [2.52.0] Ajout rapport d'activité sur le site

- src/EventSubscriber/ExpiredPasswordSubscriber.php
[Ticket](https://trello.com/c/kYyw177o/4964-5-enqu%C3%AAte-5h-etqu-si-mon-mdp-nest-plus-%C3%A0-jour-et-donc-%C3%A0-modifier-alors-que-mfa-activ%C3%A9-je-dois-pouvoir-renvoyer-le-code-de-valida)
> :bug: [UpdatePassword] Fix redirection when 2fa is enabled

- src/DataFixtures/v2/ClientFixture.php
- src/DataFixtures/v2/ClientRelayFixture.php
- tests/v2/API/v3/AbstractApiTest.php
- tests/v2/API/v3/Beneficiary/CreateTest.php
- tests/v2/API/v3/Beneficiary/SearchTest.php
[Ticket](https://trello.com/c/VyTLEVFp/4974-api-v3-rp-cfn-attention-post-estim-une-semaine-environ?filter=member:nilslapotre5)
> :heavy_check_mark: Test API v3

- src/EventSubscriber/AbstractWebUserSubscriber.php
> :bug: [PasswordPolicy] Fix redirection when 2FA is enabled

- src/Admin/UserSimpleAdmin.php
[Ticket](https://trello.com/c/GIpkqFwF/4931-3-enqu%C3%AAte-ajouter-une-contrainte-sur-le-champ-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-dans-ladmin)
> Ajouter une contrainte sur le champ numéro de téléphone dans l'admin

- templates/v2/vault/document/share.html.twig
> :lipstick: [SendDocument] Update UI

- src/ListenerV2/CreatorListener.php
- src/ManagerV2/DocumentManager.php
- src/ManagerV2/FolderManager.php
- tests/v2/Manager/DocumentManager/CreateDocumentFromFileTest.php
[Ticket](https://trello.com/c/wE7NXqFs/5014-si-un-document-est-ajout%C3%A9-en-automatiquement-depuis-rosalie-alors-il-est-indique-par-cr%C3%A9er-par-client-rosalie)
> Si un document est ajouté en automatiquement depuis Rosalie, alors il est indique par "Créé par (client)" = Rosalie

- templates/v2/vault/document/share.html.twig
> :lipstick: [SendDocument] Add condition on title

- src/ListenerV2/CreatorListener.php
- src/ManagerV2/DocumentManager.php
- src/ManagerV2/FolderManager.php
- tests/v2/Manager/DocumentManager/CreateDocumentFromFileTest.php
[Ticket](https://trello.com/c/wE7NXqFs/5014-si-un-document-est-ajout%C3%A9-en-automatiquement-depuis-rosalie-alors-il-est-indique-par-cr%C3%A9er-par-client-rosalie)
> [2.54.0] Si un document est ajouté en automatiquement depuis Rosalie, alors il est indique par "Créé par (client)" = Rosalie

- src/DataFixtures/v2/MemberFixture.php
- src/EventSubscriber/ExpiredPasswordSubscriber.php
- tests/v2/Controller/SecurityController/RedirectUserTest.php
[Ticket](https://trello.com/c/7ymWJGWS/5031-bug-premi%C3%A8re-visite-mdp-expir%C3%A9-pro)
> :bug: [FirstVisit] Fix bug when pro password is expired

- src/Admin/MembreAdmin.php
- src/Entity/Beneficiaire.php
- src/Entity/User.php
[Ticket](https://trello.com/c/8qzLRH5t/5036-2-anonymization-cfn-les-dates-de-naissance-ne-sont-pas-anonymis%C3%A9es)
[Ticket](https://trello.com/c/YNMlexqL/5010-1-etqa-quand-jajoute-des-centres-%C3%A0-un-pro-je-vois-un-message-de-pr%C3%A9vention-sur-les-droits-du-pro)
> Message de prévention sur les droits du pro + Anonymization CFN - Les dates de naissance ne sont pas anonymisées

- src/EventSubscriber/AbstractWebUserSubscriber.php
[Ticket](https://trello.com/c/21K9CG6g/5023-bug-password-policy-2fa)
> [2.55.0] :bug: [PasswordPolicy] Fix redirection when 2FA is enabled

- src/Admin/BeneficiaireAdmin.php
- src/Admin/UserSimpleAdmin.php
[Ticket](https://trello.com/c/GIpkqFwF/4931-3-enqu%C3%AAte-ajouter-une-contrainte-sur-le-champ-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-dans-ladmin)
> [2.55.0] Ajouter une contrainte sur le champ numéro de téléphone dans l'admin

- src/Api/State/BeneficiaryStateProcessor.php
> :bug: [APIV3/LinkBeneficiary] Fix strange personal data update

- assets/controllers/ajax_alert_controller.js
- assets/controllers/helpers/swal_helper.js
[Ticket](https://trello.com/c/P9sfkEV7/5043-1-etqp-quand-je-retire-un-b%C3%A9n%C3%A9ficiaire-dun-relai-je-vois-le-bouton-sur-la-modale-de-confirmation)
> ETQP, quand je retire un bénéficiaire d'un relai, je vois le bouton sur la modale de confirmation

- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
[Ticket](https://trello.com/c/V4EPbyOg/4294-5-etqp-quand-jaffilie-un-b%C3%A9n%C3%A9ficiaire-existant-%C3%A0-un-relai-linterface-est-harmonis%C3%A9e-avec-laffiliation-dun-professionnel-5)
> :lipstick: [AffiliateBenef] Removed useless br element

- assets/controllers/modal_controller.js
- templates/v2/vault/document/_card.html.twig
- templates/v2/vault/document/modal.html.twig
[Ticket](https://trello.com/c/24efG1Gg/5016-3-etqu-quand-je-clique-sur-un-document-word-png-etc-je-le-visualise-directement-depuis-le-site-sur-une-modale)
> ETQU, quand je clique sur un document (word, png, etc), je le visualise directement depuis le site sur une modale

- src/DataFixtures/v2/MemberFixture.php
- src/EventSubscriber/ExpiredPasswordSubscriber.php
- tests/v2/Controller/SecurityController/RedirectUserTest.php
[Ticket](https://trello.com/c/7ymWJGWS/5031-bug-premi%C3%A8re-visite-mdp-expir%C3%A9-pro)
> [2.56.0] :bug: [FirstVisit] Fix bug when pro password is expired

- templates/v2/user_affiliation/beneficiary/_relays_card.html.twig
- templates/v2/user_affiliation/beneficiary/relays_form.html.twig
- translations/messages.ar.yml
- translations/messages.de.yml
- translations/messages.en.yml
- translations/messages.es.yml
- translations/messages.fa.yml
- translations/messages.fr.yml
- translations/messages.it.yml
- translations/messages.ps.yml
- translations/messages.ru.yml
[Ticket](https://trello.com/c/V4EPbyOg/4294-5-etqp-quand-jaffilie-un-b%C3%A9n%C3%A9ficiaire-existant-%C3%A0-un-relai-linterface-est-harmonis%C3%A9e-avec-laffiliation-dun-professionnel)
> [2.56.0] Feature/affiliate beneficiary rework

- src/Domain/Anonymization/Anonymizer/BeneficiaryFilterAnonymizer.php
- src/Domain/Anonymization/Anonymizer/UserFilterAnonymizer.php
- src/Entity/Beneficiaire.php
[Ticket](https://trello.com/c/8qzLRH5t/5036-22-anonymization-cfn-les-dates-de-naissance-ne-sont-pas-anonymis%C3%A9es)
> :bug: [Anonymization] Filter beneficiaries for anonymisation

- src/Admin/MembreAdmin.php
- src/Domain/Anonymization/Anonymizer/BeneficiaryFilterAnonymizer.php
- src/Domain/Anonymization/Anonymizer/UserFilterAnonymizer.php
- src/Entity/Beneficiaire.php
- src/Entity/User.php
[Ticket](https://trello.com/c/8qzLRH5t/5036-2-anonymization-cfn-les-dates-de-naissance-ne-sont-pas-anonymis%C3%A9es)
[Ticket](https://trello.com/c/YNMlexqL/5010-1-etqa-quand-jajoute-des-centres-%C3%A0-un-pro-je-vois-un-message-de-pr%C3%A9vention-sur-les-droits-du-pro)
> [2.56.0] Message de prévention sur les droits du pro + Anonymization CFN - Les dates de naissance ne sont pas anonymisées

- assets/controllers/ajax_toggle_controller.js
- templates/v2/vault/components/_toggle_visibility_button.html.twig
> :recycle: [ToggleVisibility] Display tooltip depending on visibility

- src/Admin/BeneficiaireAdmin.php
[Ticket](https://trello.com/c/utGbRnyt/5015-5-enqu%C3%AAte-le-filtre-ne-fonctionne-pas-lorsquil-y-a-beaucoup-de-condition)
> Le filtre ne fonctionne pas lorsqu'il y a beaucoup de condition

- src/Admin/BeneficiaireAdmin.php
> :recycle: [BeneficiaireAdmin] Fix aliases

- src/Api/State/BeneficiaryStateProcessor.php
> [feature/api-v3-pro-interop] :bug: [APIv3/LinkBeneficiary] Fix strange personal data update

- config/packages/monolog.yaml
> :bug: [Monolog] Add missing channel for prod

- config/packages/admin.yaml
- config/packages/security.yaml
- config/packages/sonata_admin.yaml
- src/Admin/FeatureToggle.php
- src/Checker/FeatureFlagChecker.php
- src/ControllerV2/GdprController.php
- src/ControllerV2/UserController.php
- src/Domain/TermsOfUse/TermsOfUseHelper.php
- src/Entity/Attributes/FeatureFlag.php
- src/EventSubscriber/AbstractWebUserSubscriber.php
- src/EventSubscriber/CheckAcceptedTermsOfUseSubscriber.php
- src/Helper/TermsOfUseHelper.php
- src/Migrations/Version20240708142111.php
- src/Repository/FeatureFlagRepository.php
- src/Twig/ExtensionV2/FeatureFlagExtension.php
- templates/v2/footer.html.twig
- templates/v2/user/first_visit/_new_cgs_frame.html.twig
- templates/v2/user/first_visit/cgs.html.twig
[Ticket](https://trello.com/c/vTWq9S0W/5029-8-etqu-je-dois-accepter-les-nouvelles-cgu-cgs-politiques-de-confidentialit%C3%A9-en-attente-fichier-cgs)
> Nouvelles CGU

- templates/v2/vault/document/_card.html.twig
- templates/v2/vault/document/_thumbnail.html.twig
> :recycle: [ModalDoc] Add modal open on thumbnail too

- src/Controller/Rest/V3/LinkedCentersController.php
- src/Entity/Centre.php
https://trello.com/c/xEUHs4mZ/4657-8-etqa-je-sais-si-un-centre-rp-est-li%C3%A9-%C3%A0-un-centre-cfn-gr%C3%A2ce-%C3%A0-son-id
> (8) ETQA, je sais si un centre RP est lié à un centre CFN grâce à son ID

- assets/controllers/modal_controller.js
- templates/v2/vault/document/_card.html.twig
- templates/v2/vault/document/_thumbnail.html.twig
- templates/v2/vault/document/modal.html.twig
[Ticket](https://trello.com/c/24efG1Gg/5016-3-etqu-quand-je-clique-sur-un-document-word-png-etc-je-le-visualise-directement-depuis-le-site-sur-une-modale)
> [2.58.0] ETQU, quand je clique sur un document (word, png, etc), je le visualise directement depuis le site sur une modale

- src/Admin/BeneficiaireAdmin.php
[Ticket](https://trello.com/c/utGbRnyt/5015-5-enqu%C3%AAte-le-filtre-ne-fonctionne-pas-lorsquil-y-a-beaucoup-de-condition)
> [2.58.0] Le filtre ne fonctionne pas lorsqu'il y a beaucoup de condition

- config/packages/admin.yaml
- config/packages/security.yaml
- config/packages/sonata_admin.yaml
- src/Admin/FeatureToggle.php
- src/Admin/UserSimpleAdmin.php
- src/Checker/FeatureFlagChecker.php
- src/ControllerV2/GdprController.php
- src/ControllerV2/UserController.php
- src/Domain/TermsOfUse/TermsOfUseHelper.php
- src/Entity/Attributes/FeatureFlag.php
- src/EventSubscriber/AbstractWebUserSubscriber.php
- src/EventSubscriber/CheckAcceptedTermsOfUseSubscriber.php
- src/Helper/TermsOfUseHelper.php
- src/Migrations/Version20240708142111.php
- src/Repository/FeatureFlagRepository.php
- src/Twig/ExtensionV2/FeatureFlagExtension.php
- templates/v2/footer.html.twig
- templates/v2/user/first_visit/_new_cgs_frame.html.twig
- templates/v2/user/first_visit/cgs.html.twig
[Ticket](https://trello.com/c/vTWq9S0W/5029-8-etqu-je-dois-accepter-les-nouvelles-cgu-cgs-politiques-de-confidentialit%C3%A9-en-attente-fichier-cgs-8)
>  ETQU, je dois accepter les nouvelles CGU

- config/packages/admin.yaml
- config/packages/security.yaml
- config/packages/sonata_admin.yaml
- src/Admin/FeatureToggle.php
- src/Admin/UserSimpleAdmin.php
- src/Checker/FeatureFlagChecker.php
- src/ControllerV2/GdprController.php
- src/ControllerV2/UserController.php
- src/Domain/TermsOfUse/TermsOfUseHelper.php
- src/Entity/Attributes/FeatureFlag.php
- src/EventSubscriber/AbstractWebUserSubscriber.php
- src/EventSubscriber/CheckAcceptedTermsOfUseSubscriber.php
- src/Helper/TermsOfUseHelper.php
- src/Migrations/Version20240708142111.php
- src/Repository/FeatureFlagRepository.php
- src/Twig/ExtensionV2/FeatureFlagExtension.php
- templates/v2/footer.html.twig
- templates/v2/user/first_visit/_new_cgs_frame.html.twig
- templates/v2/user/first_visit/cgs.html.twig
[Ticket](https://trello.com/c/vTWq9S0W/5029-8-etqu-je-dois-accepter-les-nouvelles-cgu-cgs-politiques-de-confidentialit%C3%A9-en-attente-fichier-cgs)
> [2.59.0] Nouvelles CGU

- src/Controller/Rest/V3/LinkedCentersController.php
- src/Entity/Centre.php
(8) ETQA, je sais si un centre RP est lié à un centre CFN grâce à son ID
> [2.59.0] (8) ETQA, je sais si un centre RP est lié à un centre CFN grâce à son ID

- src/Domain/Anonymization/AnonymizationHelper.php
- src/Entity/Beneficiaire.php
[Ticket](https://trello.com/c/mgpEnIND/5109-etqu-quand-jexporte-mes-actions-collectives-chaque-valeur-dans-les-cellules-correspond-à-la-colonne-dans-laquelle-elle-se-trouve)
> :sparkles: [Beneficiary] Anonymize secret answer

- config/packages/monolog.yaml
[Ticket](https://trello.com/c/Xp4MbyzG/5085-2-suppression-des-logs)
> :loud_sound: [Logs] Added log rotation

- src/Admin/BeneficiaireAdmin.php
[Ticket](https://trello.com/c/2EYQrsMD/5063-8-enqu%C3%AAte-etqa-quand-je-filtre-les-b%C3%A9n%C3%A9ficiaires-sur-plusieurs-crit%C3%A8res-cumul%C3%A9s-je-dois-pouvoir-voir-le-r%C3%A9sultat)
> :bug: [BenefAdmin] Fix a few filter bugs

- deploy.php
[Ticket](https://trello.com/c/NB6r5CSJ/5120-enqu%C3%AAte-d%C3%A9ploiement)
> :bug: :rocket: [Deploy] Fix deploy script

- config/packages/monolog.yaml
[Ticket](https://trello.com/c/Xp4MbyzG/5085-2-suppression-des-logs)
> [RELEASE] :loud_sound: [Logs] Added log rotation

- src/Domain/Anonymization/AnonymizationHelper.php
- src/Entity/Beneficiaire.php
[Ticket](https://trello.com/c/mgpEnIND/5109-etqu-quand-jexporte-mes-actions-collectives-chaque-valeur-dans-les-cellules-correspond-à-la-colonne-dans-laquelle-elle-se-trouve)
> [2.60.0] :sparkles: [Beneficiary] Anonymize secret answer

- src/Admin/BeneficiaireAdmin.php
[Ticket](https://trello.com/c/2EYQrsMD/5063-8-enqu%C3%AAte-etqa-quand-je-filtre-les-b%C3%A9n%C3%A9ficiaires-sur-plusieurs-crit%C3%A8res-cumul%C3%A9s-je-dois-pouvoir-voir-le-r%C3%A9sultat)
> [RELEASE] :bug: [BenefAdmin] Fix a few filter bugs

- deploy.php
[Ticket](https://trello.com/c/NB6r5CSJ/5120-enqu%C3%AAte-d%C3%A9ploiement)
> [2.60.0] :bug: :rocket: [Deploy] Fix deploy script

- src/Domain/TermsOfUse/TermsOfUseHelper.php
- src/Entity/User.php
- src/EventSubscriber/Api/Oauth2ResponseSubscriber.php
- src/EventSubscriber/Api/Oauth2TokenIssuedSubscriber.php
- src/Manager/FixtureManager.php
- src/ServiceV2/GdprService.php
- tests/v1/Controller/Rest/AbstractControllerTest.php
- tests/v1/Controller/Rest/BeneficiaireRestV2ControllerTest.php
- tests/v2/Service/GdprServiceTest.php
[(8) ETQU, je dois accepter les nouvelles CGU, CGS, politiques de confidentialité,... [ATTENTE FICHIER CGS]](https://trello.com/c/x6jm180H/5008-8-etqu-je-dois-accepter-les-nouvelles-cgu-cgs-politiques-de-confidentialit%C3%A9-attente-fichier-cgs)
> :sparkles: [Appli - CGS] Prepare route to redirect to cgs post login

- translations/messages.ar.yml
- translations/messages.de.yml
- translations/messages.en.yml
- translations/messages.es.yml
- translations/messages.fa.yml
- translations/messages.fr.yml
- translations/messages.it.yml
- translations/messages.ps.yml
- translations/messages.ru.yml
> L10n main -> dev

- config/packages/doctrine.yaml
- rector.php
- src/Admin/UserSimpleAdmin.php
- src/Entity/Attributes/ClientPermission.php
- src/Entity/Attributes/ResetPasswordRequest.php
- src/Entity/Beneficiaire.php
- src/Entity/BeneficiaireCentre.php
- src/Entity/Client.php
- src/Entity/Document.php
- src/Entity/Dossier.php
- src/Entity/FaqQuestion.php
- src/Entity/Membre.php
- src/Entity/SharedDocument.php
- src/Entity/Verbatim.php
- src/Repository/ClientPermissionRepository.php
- src/RepositoryV2/ResetPasswordRequestRepository.php
- src/ServiceV2/ResettingService.php
- tests/Factory/ResetPasswordRequestFactory.php
> Merge back

- src/Admin/FolderIconAdmin.php
- src/ControllerV2/BeneficiaryPersonalDataController.php
- src/ControllerV2/FolderController.php
- src/FormV2/FolderType.php
- templates/v2/vault/folder/rename.html.twig
> :recycle: [FolderIcon] Perform a few fixes

- src/EventSubscriber/Api/Oauth2UserResolveSubscriber.php
> [2.61.2] :bug: [Oauth2UserResolveSubscriber] Fix missing null check

- src/Api/Extension/ClientResourceCollectionExtension.php
- src/Api/State/BeneficiaryStateProcessor.php
- src/ServiceV2/Helper/RelayAssignationHelper.php
- tests/v2/API/v3/Beneficiary/AddExternalLinkTest.php
- tests/v2/API/v3/Beneficiary/CreateTest.php
[Ticket](https://trello.com/c/FlR70L67/5139-api-v3-probl%C3%A8me-association-de-cfn-existant)
> 🐛 [APIv3] Fix bug when adding external link to beneficiary

- src/EventSubscriber/Api/Oauth2ResponseSubscriber.php
> :recycle: [Appli/CGU] Remove accepted cgu check

- src/ControllerV2/GdprController.php
- templates/home/footer.html.twig
[Ticket](https://trello.com/c/pObpCZEV/5140-fix-sur-le-nom-de-lannexe-des-cgs)
> :bug: [CGS] Fix error in annexe name

- src/Validator/Constraints/Rappel/EntityValidator.php
[Ticket](https://trello.com/c/gPr1yRrI/5144-fix-rappels-apiv3)
> :bug: [APIv3] Fix bug when adding reminder

- src/Api/Extension/ClientResourceCollectionExtension.php
- src/Api/State/BeneficiaryStateProcessor.php
- src/ServiceV2/Helper/RelayAssignationHelper.php
- tests/v2/API/v3/Beneficiary/AddExternalLinkTest.php
- tests/v2/API/v3/Beneficiary/CreateTest.php
[Ticket](https://trello.com/c/FlR70L67/5139-api-v3-probl%C3%A8me-association-de-cfn-existant)
> [2.63.0] API v3 - Problème association de CFN existant

- src/ControllerV2/GdprController.php
- templates/home/footer.html.twig
[Ticket](https://trello.com/c/pObpCZEV/5140-fix-sur-le-nom-de-lannexe-des-cgs)
> [2.63.0] :bug: [CGS] Fix error in annexe name

- src/EventSubscriber/Api/Oauth2ResponseSubscriber.php
> :sparkles: [Oauth2ResponseSubscriber] Enable cgs accepted check

- src/EventSubscriber/Api/Oauth2ResponseSubscriber.php
> [Release] :sparkles: [Oauth2ResponseSubscriber] Enable cgs accepted check

- src/ControllerV2/FolderIconController.php
- src/Entity/Dossier.php
[Ticket](https://trello.com/c/Hso16Zb3/5041-3-etqu-je-peux-ajouter-une-image-%C3%A0-la-cr%C3%A9ation-update-dun-dossier-dans-le-cfn)
> :sparkles: [Folder icons] Create api route to get folder icons

- src/Controller/Rest/DossierRestV2Controller.php
- src/ControllerV2/FolderIconController.php
- src/Entity/Dossier.php
> :sparkles: [Api Folder Icon] Allow to create folder with icon

- deploy.php
> :rocket: [Deploy] Add folder_icon to shared dirs

- src/Command/Scheduled/CheckAppLogsCommand.php
[Ticket](https://trello.com/c/zybzF3eC/5152-r%C3%A9parer-les-alertes-mail-sur-les-fichiers-de-logs)
> Réparer les alertes mail sur les fichiers de logs

- src/Command/Scheduled/CheckAppLogsCommand.php
[Ticket](https://trello.com/c/zybzF3eC/5152-r%C3%A9parer-les-alertes-mail-sur-les-fichiers-de-logs)
> [2.64.0] Réparer les alertes mail sur les fichiers de logs

- src/Api/Filters/DistantIdFilter.php
> :bug: [Beneficiaries API v3] Fix bug with distant filter

- src/Validator/Constraints/Rappel/EntityValidator.php
[Ticket](https://trello.com/c/gPr1yRrI/5144-fix-rappels-apiv3)
> [2.66.0] :bug: [APIv3] Fix bug when adding reminder

- src/Validator/Constraints/Rappel/EntityValidator.php
[Ticket](https://trello.com/c/gPr1yRrI/5144-1-1-fix-rappels-apiv3)
> :bug: [APIv3/RP] Fix bug on phone number check

- src/Validator/Constraints/Rappel/EntityValidator.php
[Ticket](https://trello.com/c/gPr1yRrI/5144-1-1-fix-rappels-apiv3)
> [2.66.0] :bug: [APIv3/RP] Fix bug on phone number check

- src/Checker/FeatureFlagChecker.php
- src/Entity/Attributes/FeatureFlag.php
[Ticket](https://trello.com/c/CX99Yndc/5178-2-enqu%C3%AAte-etqa-je-dois-pouvoir-ajouter-une-affiliation-%C3%A0-un-centre)
>  ETQA je dois pouvoir ajouter une affiliation à un Centre

- src/Checker/FeatureFlagChecker.php
- src/Entity/Attributes/FeatureFlag.php
[Ticket](https://trello.com/c/CX99Yndc/5178-2-enqu%C3%AAte-etqa-je-dois-pouvoir-ajouter-une-affiliation-%C3%A0-un-centre)
> [2.66.0] ETQA je dois pouvoir ajouter une affiliation à un Centre

- src/Service/ExportService.php
[Ticket](https://trello.com/c/5DiT0dbi/5159-3-enqu%C3%AAte-3h-etqa-quand-jexporte-les-statistiques-dun-relai-je-dois-voir-la-bonne-valeur-dans-documents-provenants-de-x-cfn)
>  ETQA, quand j'exporte les statistiques d'un relai je dois voir la bonne valeur dans "Documents provenants de x CFN"

- src/ControllerV2/SharedPersonalDataController.php
- templates/v2/vault/folder/_card.html.twig
- templates/v2/vault/personal_data/_download_folder_instruction.html.twig
> :bug: [SharedFolder] Perform a few fixes

- src/Controller/Rest/DossierRestV2Controller.php
> :sparkles: [Api v2 folders icons] Enable folder icon update on patch

- src/Service/ExportService.php
[Ticket](https://trello.com/c/5DiT0dbi/5159-3-max-3h-etqa-quand-jexporte-les-statistiques-dun-relai-je-dois-voir-la-bonne-valeur-dans-documents-provenants-de-x-cfn)
> ETQA, quand j'exporte les statistiques d'un relai je dois voir la bonne valeur dans "Documents provenants de x CFN"

- config/doctrine/Dossier.orm.yml
- src/Migrations/Version20241008131622.php
- tests/v2/Entity/FolderTest.php
[Ticket](https://trello.com/c/CohBkHhV/5200-2-etqsa-je-peux-supprimer-une-image-de-dossier)
> ETQSA, je peux supprimer une image de dossier

- src/Service/ExportService.php
[Ticket](https://trello.com/c/5DiT0dbi/5159-3-enqu%C3%AAte-3h-etqa-quand-jexporte-les-statistiques-dun-relai-je-dois-voir-la-bonne-valeur-dans-documents-provenants-de-x-cfn)
> [2.68.0]  ETQA, quand j'exporte les statistiques d'un relai je dois voir la bonne valeur dans "Documents provenants de x CFN"

- templates/v2/vault/components/_toggle_visibility_button.html.twig
> :bug: [Alert] Fix untranslated message

- .github/workflows/symfony.yaml
- composer.lock
> :green_heart: [CI] Fix composer vulnerabilites check

- src/ControllerV2/ContactController.php
- src/ControllerV2/DocumentController.php
- src/ControllerV2/EventController.php
- src/ControllerV2/FolderController.php
- src/ControllerV2/NoteController.php
- src/Security/VoterV2/PersonalDataVoter.php
- src/Twig/ExtensionV2/PersonalDataActionExtension.php
- templates/v2/users_list/components/_action_dropdown.html.twig
- templates/v2/vault/components/_action_dropdown.html.twig
- templates/v2/vault/components/_action_dropdown_item.html.twig
- templates/v2/vault/contact/_card.html.twig
- templates/v2/vault/document/_card.html.twig
- templates/v2/vault/event/_card.html.twig
- templates/v2/vault/folder/_card.html.twig
- templates/v2/vault/note/_card.html.twig
- tests/v2/Controller/FolderController/DeleteTest.php
[Ticket](https://trello.com/c/HqGif92E/4803-8-etqp-je-ne-peux-pas-supprimer-de-document-sur-le-web-pas-de-bouton-supprimer)
> ETQP je ne peux pas supprimer de document sur le web => pas de bouton supprimer

- .github/workflows/symfony.yaml
- composer.lock
> [2.69.0] :green_heart: [CI] Fix composer vulnerabilites check

- src/ControllerV2/ContactController.php
- src/ControllerV2/DocumentController.php
- src/ControllerV2/EventController.php
- src/ControllerV2/FolderController.php
- src/ControllerV2/NoteController.php
- src/Security/VoterV2/PersonalDataVoter.php
- src/Twig/ExtensionV2/PersonalDataActionExtension.php
- templates/v2/users_list/components/_action_dropdown.html.twig
- templates/v2/vault/components/_action_dropdown.html.twig
- templates/v2/vault/components/_action_dropdown_item.html.twig
- templates/v2/vault/contact/_card.html.twig
- templates/v2/vault/document/_card.html.twig
- templates/v2/vault/event/_card.html.twig
- templates/v2/vault/folder/_card.html.twig
- templates/v2/vault/note/_card.html.twig
- tests/v2/Controller/FolderController/DeleteTest.php
[Ticket](https://trello.com/c/HqGif92E/4803-8-etqp-je-ne-peux-pas-supprimer-de-document-sur-le-web-pas-de-bouton-supprimer)
> [2.70.0] ETQP je ne peux pas supprimer de document sur le web => pas de bouton supprimer

- assets/controllers/ajax_toggle_controller.js
- src/Twig/ExtensionV2/PersonalDataActionExtension.php
- templates/v2/vault/contact/_card.html.twig
- templates/v2/vault/event/_card.html.twig
- templates/v2/vault/note/_card.html.twig
> Merge back main

- yarn-security-checker.sh
> [2.71.1] Feature/yarn check

- src/ControllerV2/FolderController.php
- src/Domain/Download/FolderTreeDownloader.php
- src/ManagerV2/FolderManager.php
> ETQU je peux télécharger l'ensemble de l'arborescence d'un dossier

- composer.lock
> :arrow_up: [Composer] Update symfony/*

- composer.lock
> :arrow_up: [twig/twig] 3.14.0 -> 3.14.2

- composer.lock
> [2.71.2] :arrow_up: [Composer] Update 

- config/packages/admin.yaml
- src/Admin/BeneficiaireAdmin.php
- src/Domain/Download/FolderTreeDownloader.php
> :bug: [ExportBeneficiary] Fixes

- composer.lock
> :arrow_up: [Composer] Update vulnerable packages

- composer.lock
> [2.72.0] :arrow_up: [Composer] Update vulnerable packages

- config/packages/admin.yaml
- src/Admin/BeneficiaireAdmin.php
- src/ControllerV2/BeneficiaryController.php
- src/ControllerV2/FolderController.php
- src/DataFixtures/v2/SuperAdminFixture.php
- src/Domain/Download/FolderTreeDownloader.php
- src/Domain/Export/BeneficiaryData/BeneficiaryDataExporter.php
- src/Entity/Beneficiaire.php
- src/ManagerV2/FolderManager.php
- src/Security/VoterV2/PersonalDataVoter.php
- tests/v2/Controller/Beneficiary/ExportTest.php
[Ticket](https://trello.com/c/JUZIWLnU/5265-8-etqsa-depuis-ladmin-je-peux-exporter-le-contenu-du-cfn-dun-benef)
> [Release] ETQSA, depuis l'admin je peux exporter le contenu du CFN d'un benef -> vers feature/download-folder

- composer.lock
> :arrow_up: [phpoffice] Update

- composer.lock
> [2.72.1] :arrow_up: [phpoffice] Update

- api-collections/api-v3-pwd/User/Me.bru
- api-collections/api-v3-pwd/User/Update.bru
- src/Api/State/SearchBeneficiaryProvider.php
- src/Controller/Api/MeController.php
- src/Entity/User.php
> :sparkles: [API] Add /me endpoint

- src/Provider/CentreProvider.php
[Ticket](https://trello.com/c/jh4kQIGq/5362-etqu-je-vois-les-centres-sur-la-map-de-la-home)
> ETQU Je vois les centres sur la map de la home

- src/Provider/CentreProvider.php
[Ticket](https://trello.com/c/jh4kQIGq/5362-etqu-je-vois-les-centres-sur-la-map-de-la-home)
> [2.72.2] ETQU Je vois les centres sur la map de la home

- src/Api/State/BeneficiaryStateProcessor.php
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/DataFixtures/v2/ClientBeneficiaryFixture.php
- src/DataFixtures/v2/ClientFixture.php
- src/Entity/Beneficiaire.php
- src/Entity/Client.php
- tests/v2/API/v3/Beneficiary/AddExternalLinkTest.php
- tests/v2/API/v3/Beneficiary/GetTest.php
- tests/v2/API/v3/Contact/ContactApiV3Test.php
- tests/v2/API/v3/Event/EventApiV3Test.php
- tests/v2/API/v3/Note/NoteApiV3Test.php
[Ticket](https://trello.com/c/5ZJ50Sse/5369-5-etqu-je-peux-cr%C3%A9er-plusieurs-liaisons-externe-vers-un-m%C3%AAme-cfn)
> ETQU je peux créer plusieurs liaisons externe vers un même CFN

- src/Api/State/BeneficiaryStateProcessor.php
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/DataFixtures/v2/ClientBeneficiaryFixture.php
- src/DataFixtures/v2/ClientFixture.php
- src/Entity/Beneficiaire.php
- src/Entity/Client.php
- tests/v2/API/v3/Beneficiary/AddExternalLinkTest.php
- tests/v2/API/v3/Beneficiary/GetTest.php
- tests/v2/API/v3/Contact/ContactApiV3Test.php
- tests/v2/API/v3/Event/EventApiV3Test.php
- tests/v2/API/v3/Note/NoteApiV3Test.php
[Ticket](https://trello.com/c/5ZJ50Sse/5369-5-etqu-je-peux-cr%C3%A9er-plusieurs-liaisons-externe-vers-un-m%C3%AAme-cfn)
> [2.73.0] ETQU je peux créer plusieurs liaisons externe vers un même CFN

- src/Entity/Attributes/Annexe.php
[Ticket](https://trello.com/c/QnnVK75e/5418-0-admin-annexe-fix-dune-500-%C3%A0-la-cr%C3%A9ation)
> :bug: [Annexe] Fix 500 on annexe creation

- src/Entity/Attributes/Annexe.php
[Ticket](https://trello.com/c/QnnVK75e/5418-0-admin-annexe-fix-dune-500-%C3%A0-la-cr%C3%A9ation)
> [2.74.0] :bug: [Annexe] Fix 500 on annexe creation

- composer.lock
- tests/v2/Service/GdprServiceTest.php
**Tech :**
- ⬆️ [phpspreadsheet] Upgrade
- ✅ [GDPR] Fix GDPR test with new year days count 
**Tech :**
- ✅ [Tests] Correction des tests RGPD en fonction du nb de jours dans l'année
- ⬆️ MAJ phpSpreadSheet
> :rocket: 2.74.1

- Makefile
- deploy.php
> Server migration

- Makefile
- deploy.php
> :package: Server migration

- .env
- config/packages/twig.yaml
- templates/home/footer.html.twig
- templates/home/sections/page-rp-hero-section.html.twig
[Ticket](https://trello.com/c/WN5H7vVj/5491-etqu-quand-je-clique-sur-un-lien-vers-rp-je-rejoins-le-bon-environnement)
> :recycle: [RP_ENDPOINT] Add env var

- src/Command/ToggleMaintenanceCommand.php
- src/ListenerV2/MaintenanceListener.php
- templates/bundles/TwigBundle/Exception/generic_page.html.twig
- templates/v2/maintenance/maintenance.html.twig
> Migration - Page de maintenance

- src/Provider/HomeProvider.php
- templates/home/templates/product-is-template.html.twig
[Ticket]((3) ETQVisiteur du site Reconnect, je peux accéder aux présentations des formations CFN et RP)
> (3) ETQVisiteur du site Reconnect, je peux accéder aux présentations des formations CFN et RP

- src/Provider/HomeProvider.php
- templates/home/templates/product-is-template.html.twig
[Ticket](https://trello.com/c/OP9UYgiL/5477-05-etqvisiteur-du-site-reconnect-je-vois-les-nouveaux-chiffres-de-laccompagnement-num%C3%A9rique)
> (0.5) ETQVisiteur du site Reconnect, je vois les nouveaux chiffres de l'accompagnement numérique

- translations/messages.ar.yml
- translations/messages.de.yml
- translations/messages.en.yml
- translations/messages.es.yml
- translations/messages.fa.yml
- translations/messages.fr.yml
- translations/messages.it.yml
- translations/messages.ps.yml
- translations/messages.ru.yml
> L10n main->dev

- src/Provider/HomeProvider.php
- templates/home/templates/product-is-template.html.twig
[Ticket](https://trello.com/c/GgbMH3XC/5417-3-etqvisiteur-du-site-reconnect-je-peux-acc%C3%A9der-aux-pr%C3%A9sentations-des-formations-cfn-et-rp)
> 📦(3) ETQVisiteur du site Reconnect, je peux accéder aux présentations des formations CFN et RP

- composer.json
- composer.lock
> :package: :arrow_up: [phpspreadsheet] Upgrade to 1.29.9

- src/Command/ToggleMaintenanceCommand.php
- src/ListenerV2/MaintenanceListener.php
- templates/bundles/TwigBundle/Exception/generic_page.html.twig
- templates/v2/maintenance/maintenance.html.twig
[Ticket](https://trello.com/c/oOklQipv/5505-migration-page-de-maintenance)
> :package: Migration - Page de maintenance

- translations/messages.fr.yml
> New translations messages.fr.yml (French)

- src/Provider/HomeProvider.php
- templates/home/templates/product-is-template.html.twig
[Ticket](https://trello.com/c/OP9UYgiL/5477-05-etqvisiteur-du-site-reconnect-je-vois-les-nouveaux-chiffres-de-laccompagnement-num%C3%A9rique)
> 📦(0.5) ETQVisiteur du site Reconnect, je vois les nouveaux chiffres de l'accompagnement numérique

- src/Provider/HomeProvider.php
- templates/home/templates/product-is-template.html.twig
**New :**
- :sparkles: [Home] Update digital care stats
**Nouveautés :**
- :sparkles: [Home] Mise à jour des nouveaux chiffres de l'accompagnement numérique
> :rocket: 2.76.1

- tests/v2/Manager/FolderManager/getRootFoldersTest.php
> :white_check_mark: [FolderManager] Update getRootFoldersTest

- translations/messages.de.yml
- translations/messages.fr.yml
[Ticket](https://trello.com/c/2XGbcz67/5551-1-etqvisiteur-du-site-reconnect-je-vois-les-chiffres-de-satisfaction-de-la-formation-aux-outils-mis-%C3%A0-jour)
> l10n_main -> dev

- templates/home/sections/digital_cares_section.html.twig
[Ticket](https://trello.com/c/s6BpHDNx/5498-2-ajouter-un-bouton-retrouvez-ici-la-version-accessible-sur-la-page-de-laccompagnement-num%C3%A9rique)
> Ajouter un bouton "Retrouvez ici la version accessible" sur la page de l'accompagnement numérique

- templates/home/sections/digital_cares_section.html.twig
[Ticket](https://trello.com/c/s6BpHDNx/5498-2-ajouter-un-bouton-retrouvez-ici-la-version-accessible-sur-la-page-de-laccompagnement-num%C3%A9rique)
> (2) Ajouter un bouton "Retrouvez ici la version accessible" sur la page de l'accompagnement numérique

- templates/home/sections/digital_cares_section.html.twig
**New :**
- :sparkles: [DigitalCare] Add accessible catalog version
**Improvement :**
- :lipstick: [Home] Add missing translations
- :recycle: [Home] Update satisfaction rates on training
**Nouveautés :**
- :sparkles: [AccompagnementNumérique] Ajouter un bouton "Retrouvez ici la version accessible" sur la page de l'accompagnement numérique 
**Améliorations :**
- :lipstick: [Home] Ajout de traductions manquantes
- :recycle: [Home] Chiffres de satisfaction de la formation aux outils mis à jour
> :rocket: 2.77.0

- tests/v2/Service/GdprServiceTest.php
> ✅ [Gdpr] Fixed tests

- tests/v2/Service/GdprServiceTest.php
**Tech :**
- ✅ [Gdpr] Fixed tests
**Tech :**
- ✅ [RGPD] Fix d'un cas de test
> :rocket: 2.77.1

- templates/home/sections/feature-rp-section.html.twig
[Ticket](https://trello.com/c/Dw9xnMnU/5549-3-ajout-logo-s%C3%A9gur-page-accueil-page-pr%C3%A9sentation-rp8)
> (3) Ajout logo Ségur page accueil + page présentation RP[8]

- Makefile
- deploy.php
[Ticket](https://trello.com/c/EDYKpD2h/5572-setup-script-deploy-prod)
> Setup script deploy prod de migration

- config/packages/security.yaml
- src/ControllerV2/MainController.php
- tests/v2/Controller/MainController/ReconnectProPageTest.php
[Ticket](https://trello.com/c/qXpVKyFo/5556-2-verbatim-solution-pro-reconnect-pro)
> (2) Verbatim "Solution Pro" --> "Reconnect Pro"

- src/Provider/HomeProvider.php
- templates/home/sections/feature-rp-section.html.twig
[Ticket](https://trello.com/c/Dw9xnMnU/5549-3-ajout-logo-s%C3%A9gur-page-accueil-page-pr%C3%A9sentation-rp8)
> 📦(3) Ajout logo Ségur page accueil + page présentation RP

- config/packages/security.yaml
- src/ControllerV2/MainController.php
- tests/v2/Controller/MainController/ReconnectProPageTest.php
[Ticket](https://trello.com/c/qXpVKyFo/5556-2-verbatim-solution-pro-reconnect-pro)
> 📦(2) Verbatim "Solution Pro" --> "Reconnect Pro"

- templates/home/sections/our-solutions-section.html.twig
> 🩹 [Home] Fix qualiopi css

- templates/home/sections/our-solutions-section.html.twig
> [Home] Fix qualiopi css

- src/Command/DataMigration/MigrateCreeParCommand.php
[Ticket](https://trello.com/c/5FMvEulP/5599-commande-pour-migrer-creeparid)
> Commande pour migrer creePar_id

- src/Domain/Download/FolderTreeDownloader.php
- src/Entity/Dossier.php
[Ticket](https://trello.com/c/Ad6I3YkI/5584-etqu-je-peux-t%C3%A9l%C3%A9charger-un-dossier-dont-le-nom-comporte-un-accent)
> ETQU, je peux télécharger un dossier dont le nom comporte un accent

- templates/v2/vault/document/_card.html.twig
[Ticket](https://trello.com/c/DC97jeM7/5585-etqu-je-peux-drag-drop-mes-documents-dans-un-dossier)
> ETQU, je peux drag & drop mes documents dans un dossier

- src/ControllerV2/BeneficiaryAffiliationController.php
- src/ControllerV2/ProController.php
[Ticket](https://trello.com/c/VqnkmfJx/5629-3-enqu%C3%AAte-3h-etqp-je-dois-pouvoir-rechercher-un-pro-existant-qui-a-un-espace-dans-son-nom-lors-de-laffiliation-%C3%A0-un-relai)
> ETQP, je dois pouvoir rechercher un pro existant qui a un espace dans son nom lors de l'affiliation à un relai

- Makefile
- deploy.php
[Ticket](https://trello.com/c/ktwDjXfF/5652-maj-script-deploy)
> Migration deploy updates

- templates/v2/vault/document/_card.html.twig
- templates/v2/vault/document/_list.html.twig
- templates/v2/vault/folder/_card.html.twig
[Ticket](https://trello.com/c/S1yUeQOF/5171-3-templates-list-docs-dossier-voir-pour-conditionner-lexistence-de-la-colonne-de-visibilit%C3%A9-en-fonction-de-lutilisateur-connect%C3%A9)
> 📦 (3) Templates list docs / dossier -> Voir pour conditionner l'existence de la colonne de visibilité en fonction de l'utilisateur connecté

- src/ControllerV2/BeneficiaryAffiliationController.php
- src/ControllerV2/ProController.php
[Ticket](https://trello.com/c/VqnkmfJx/5629-3-enqu%C3%AAte-3h-etqp-je-dois-pouvoir-rechercher-un-pro-existant-qui-a-un-espace-dans-son-nom-lors-de-laffiliation-%C3%A0-un-relai)
> :package: ETQP, je dois pouvoir rechercher un pro existant qui a un espace dans son nom lors de l'affiliation à un relai

- templates/v2/vault/document/_card.html.twig
[Ticket](https://trello.com/c/DC97jeM7/5585-etqu-je-peux-drag-drop-mes-documents-dans-un-dossier)
> 📦 ETQU, je peux drag & drop mes documents dans un dossier

- config/packages/monolog.yaml
[Ticket](https://trello.com/c/EPD3HK9k/5581-limiter-les-fichiers-de-deprecations-conserv%C3%A9s-sur-le-serveur)
> 📦 Limiter les fichiers de deprecations conservés sur le serveur

- .github/workflows/symfony.yaml
> :wrench: [CI] Temporary disable composer audit

- .github/workflows/symfony.yaml
> :package: :wrench: [CI] Temporary disable composer audit

- src/Provider/HomeProvider.php
- templates/home/sections/digital_cares_workshop_section.html.twig
[Ticket](https://trello.com/c/LTSRPZfl/5644-2-etqvisiteur-du-site-reconnect-je-peux-acc%C3%A9der-au-certificat-qualiopi)
> ETQVisiteur du site Reconnect, je peux accéder au certificat Qualiopi

- src/Provider/HomeProvider.php
- templates/home/sections/digital_cares_workshop_section.html.twig
[Ticket](https://trello.com/c/LTSRPZfl/5644-2-etqvisiteur-du-site-reconnect-je-peux-acc%C3%A9der-au-certificat-qualiopi)
> :package: ETQVisiteur du site Reconnect, je peux accéder au certificat Qualiopi

- src/Admin/BeneficiaireAdmin.php
[Ticket](https://trello.com/c/mHi3XhFp/5656-05-etqa-lorsque-jexporte-les-b%C3%A9n%C3%A9ficiaires-je-nai-pas-de-colonne-avec-le-username)
> 📦 ETQA, lorsque j'exporte les bénéficiaires, je n'ai pas de colonne avec le username

- assets/js/home/openstreetmap-marker-generator.js
[Ticket](https://trello.com/c/WyKW1A2m/5871-3-enqu%C3%AAte-3haffichage-des-centres-sur-la-map)
> Affichage des centres sur la map

- assets/js/home/openstreetmap-marker-generator.js
[Ticket](https://trello.com/c/WyKW1A2m/5871-3-enqu%C3%AAte-3haffichage-des-centres-sur-la-map)
> :package: Affichage des centres sur la map

- api-collections/api-v3-pwd/Personal Data/Events/Create.bru
- api-collections/api-v3-pwd/Personal Data/Events/Update.bru
[Ticket](https://trello.com/c/UYmQLARd/5717-3-password-grant-event)
> Password Grant - Event

- api-collections/api-v3-pwd/Personal Data/Events/Create.bru
- api-collections/api-v3-pwd/Personal Data/Events/Update.bru
[Ticket](https://trello.com/c/UYmQLARd/5717-3-password-grant-event)
> 🔀 Password Grant - Event

- api-collections/api-v3-pwd/Personal Data/Notes/Update.bru
[Ticket](https://trello.com/c/4u3Meu22/5719-3-password-grant-notes)
>  Password Grant - Notes

- api-collections/api-v3-pwd/Personal Data/Notes/Update.bru
[Ticket](https://trello.com/c/4u3Meu22/5719-3-password-grant-notes)
> 🔀  Password Grant - Notes

- api-collections/api-v3-pwd/Personal Data/Folders/Create.bru
- api-collections/api-v3-pwd/Personal Data/Folders/Delete.bru
- api-collections/api-v3-pwd/Personal Data/Folders/Get.bru
- api-collections/api-v3-pwd/Personal Data/Folders/GetCollection.bru
- api-collections/api-v3-pwd/Personal Data/Folders/Update.bru
- src/Entity/Dossier.php
[Ticket](https://trello.com/c/sDod7j9S/5718-password-grant-folders)
> 🔀 Password Grant - Folders

- src/Api/Extension/FilterUserCollectionsExtension.php
- src/Entity/Attributes/Centre.php
[Ticket](https://trello.com/c/3p9OfTOS/5720-password-grant-relays)
> 🔀 Password Grant - Relays

- api-collections/api-v3-client-credentials/Personal Data/Folders/Create.bru
- src/Api/State/PersonalDataStateProcessor.php
- src/Entity/Attributes/DonneePersonnelle.php
- src/Entity/Attributes/Dossier.php
[Ticket](https://trello.com/c/xXNztX81/5930-5-api-v3-client-credentials-post-folder)
> API v3 - Client credentials - POST Folder

- src/Entity/Dossier.php
- tests/v2/API/v3/Document/DocumentAPIv3Test.php
- tests/v2/API/v3/Folder/FolderApiV3Test.php
[Ticket](https://trello.com/c/VnewxasK/5933-api-v3-client-credentials-tests)
> 🔀 API v3 - Client credentials - Tests

- src/Controller/Rest/EvenementRestV2Controller.php
- src/Entity/Attributes/Beneficiaire.php
> :bug: [Events] Fix 500 on api v2 list endpoint

- src/Controller/Rest/EvenementRestV2Controller.php
- src/Entity/Attributes/Beneficiaire.php
> :package: [Events] Fix 500 on api v2 list endpoint

- src/Admin/MembreAdmin.php
- src/Entity/Attributes/BeneficiaireCentre.php
- src/Entity/Attributes/MembreCentre.php
- src/Entity/Attributes/UserCentre.php
> :recycle: [MembreAdmin] Fix 500

- src/Admin/MembreAdmin.php
- src/Entity/Attributes/BeneficiaireCentre.php
- src/Entity/Attributes/MembreCentre.php
- src/Entity/Attributes/UserCentre.php
> :package: [MembreAdmin] Fix 500

- src/Command/EnableApiClientCommand.php
[Ticket](https://trello.com/c/tHhrGmfM/5959-activer-client-de-test-softeam-tous-les-lundis)
> Activer client de test Softeam tous les lundis 

- src/Entity/Attributes/User.php
> :bug: [User] Restore password updated at lifecyclecallback

- api-collections/api-v3-client-credentials/Beneficiaries/Add external link.bru
- api-collections/api-v3-pwd/Beneficiaries/GetCollection.bru
- src/Api/State/BeneficiaryStateProcessor.php
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/DataFixtures/v2/ClientBeneficiaryFixture.php
- src/DataFixtures/v2/ClientRelayFixture.php
- src/Entity/Attributes/Beneficiaire.php
- src/Entity/Attributes/Centre.php
- src/ServiceV2/Helper/RelayAssignationHelper.php
- tests/v2/API/v3/Beneficiary/AddExternalLinkTest.php
[Ticket](https://trello.com/c/rQzw2mqi/5979-5-etqu-sur-rp-je-ne-peux-pas-associer-un-m%C3%AAme-cfn-%C3%A0-deux-m%C3%A9nages-diff%C3%A9rents-dun-m%C3%AAme-centre-8)
> ETQU, sur RP je ne peux pas associer un même CFN à deux ménages différents d'un même centre - dev

- config/packages/security.yaml
[Ticket](https://trello.com/c/DOtNCQob/5973-3-etqa-je-nai-pas-acc%C3%A8s-%C3%A0-la-section-super-admin)
> ETQA je n'ai pas accès à la section super admin

- src/DataFixtures/v2/MemberFixture.php
- tests/v2/Controller/GdprController/UpdatePasswordTest.php
[Ticket](https://trello.com/c/bZ7YepWR/5964-3-mot-de-passe-expir%C3%A9-ajouter-des-tests)
> Mot de passe expiré -> Ajouter des tests

- config/packages/sonata_admin.yaml
[Ticket](https://trello.com/c/2u223FOc/5974-etqa-je-nai-pas-acc%C3%A8s-%C3%A0-longlet-super-admin)
> 📦 ETQA je ne vois pas l'onglet Client

- config/packages/security.yaml
[Ticket](https://trello.com/c/DOtNCQob/5973-3-etqa-je-nai-pas-acc%C3%A8s-%C3%A0-la-section-super-admin)
> :package: ETQA je n'ai pas accès à la section super admin

- api-collections/api-v3-client-credentials/API v3 Client Credentials/Beneficiaries/Add external link.bru
- api-collections/api-v3-client-credentials/API v3 Client Credentials/Beneficiaries/Beneficiaries.bru
- src/Api/State/BeneficiaryStateProcessor.php
- src/DataFixtures/v2/BeneficiaryFixture.php
- src/DataFixtures/v2/ClientBeneficiaryFixture.php
- src/DataFixtures/v2/ClientRelayFixture.php
- src/Entity/Attributes/Beneficiaire.php
- src/Entity/Attributes/Centre.php
- src/ServiceV2/Helper/RelayAssignationHelper.php
- tests/v2/API/v3/Beneficiary/AddExternalLinkTest.php
[Ticket](https://trello.com/c/rQzw2mqi/5979-5-etqu-sur-rp-je-ne-peux-pas-associer-un-m%C3%AAme-cfn-%C3%A0-deux-m%C3%A9nages-diff%C3%A9rents-dun-m%C3%AAme-centre-8)
> 📦 ETQU, sur RP je ne peux pas associer un même CFN à deux ménages différents d'un même centre 

- src/DataFixtures/v2/MemberFixture.php
- tests/v2/Controller/GdprController/UpdatePasswordTest.php
[Ticket](https://trello.com/c/bZ7YepWR/5964-3-mot-de-passe-expir%C3%A9-ajouter-des-tests)
> 📦 Mot de passe expiré -> Ajouter des tests

- deploy.php
> :recycle: [deploy] Define keep release globally

- src/Entity/Attributes/AccessToken.php
- src/Entity/Attributes/Centre.php
- src/Entity/Attributes/ClientBeneficiaire.php
- src/Entity/Attributes/ClientCentre.php
- src/Entity/Attributes/ConsultationBeneficiaire.php
- src/Entity/Attributes/Creator.php
- src/Entity/Attributes/Evenement.php
- src/Entity/Attributes/Gestionnaire.php
- src/Entity/Attributes/Rappel.php
- src/Entity/Attributes/RefreshToken.php
- src/Entity/Attributes/SMS.php
- src/Entity/Attributes/SharedDocument.php
- src/Entity/Attributes/StatistiqueCentre.php
- src/Entity/Attributes/User.php
[Ticket](https://trello.com/c/4Cl7kDLp/5943-8-fix-mappings-des-entit%C3%A9s)
>  Fix mappings des entités

- translations/messages.de.yml
- translations/messages.en.yml
- translations/messages.es.yml
- translations/messages.fa.yml
- translations/messages.fr.yml
- translations/messages.it.yml
- translations/messages.prs.yml
- translations/messages.ps.yml
- translations/messages.ru.yml
[Ticket](https://trello.com/c/IImiStam/6047-3-etqu-quand-je-suis-men%C3%A9-vers-une-page-derreur-le-message-doit-mindiquer-la-page-de-contacts-1-sprint-pr%C3%A9c%C3%A9dent)
> Crowdin to dev

- src/FormV2/UserType.php
- tests/v2/Controller/UserController/SettingsTest.php
[Ticket](https://trello.com/c/Ucz8j5th/6086-1-etqp-je-ne-peux-pas-modifier-mon-adresse-email)
> 📦 ETQP, je ne peux pas modifier mon adresse email

- config/packages/monolog.yaml
- src/Command/Scheduled/CheckDiskCapacityCommand.php
[Ticket](https://trello.com/c/vN3TIKiD/6092-5-logger-la-capacit%C3%A9-serveur-tous-les-dimanches)
> Logger la capacité serveur tous les dimanches

- api-collections/api-v3-client-credentials/Personal Data/Folders/GetCollectionTreeFromBeneficiary.bru
- config/packages/security.yaml
- src/Api/State/BeneficiaryStateProcessor.php
- src/Api/State/FolderTreeStateProvider.php
- src/DataFixtures/v2/ClientFixture.php
- src/Entity/Attributes/DonneePersonnelle.php
- src/Entity/Attributes/Dossier.php
- tests/v2/API/v3/Beneficiary/CreateTest.php
- tests/v2/API/v3/Folder/FolderApiV3Test.php
[Ticket](https://trello.com/c/Z3qviDMk/6153-2-lors-de-la-cr%C3%A9ation-dun-b%C3%A9n%C3%A9ficiaire-via-lapi-je-peux-renseigner-directement-le-mot-de-passe)
> Lors de la création d'un bénéficiaire via l'api, je peux renseigner directement le mot de passe

- config/validator/user.yml
- src/Command/ForceAdminPasswordUpdateCommand.php
- src/Command/PromptHelper.php
- src/Controller/Rest/UserRestV2Controller.php
- src/Controller/Rest/V3/UserApiController.php
- src/ControllerV2/GdprController.php
- src/ControllerV2/ProController.php
- src/ControllerV2/ResetPasswordController.php
- src/ControllerV2/UserController.php
- src/Domain/PasswordStrength/WeakPasswordUpgrader.php
- src/Entity/Attributes/BaseUser.php
- src/Entity/Attributes/User.php
- src/FormV2/ChangePasswordFormType.php
- src/ManagerV2/UserManager.php
- src/Repository/UserRepository.php
- src/ServiceV2/Helper/PasswordHelper.php
- src/Validator/Constraints/PasswordCriteria.php
- src/Validator/Constraints/PasswordCriteriaValidator.php
- templates/v2/reset_password/beneficiary/choice.html.twig
- templates/v2/reset_password/beneficiary/secret_answer.html.twig
- templates/v2/reset_password/beneficiary/sms.html.twig
- templates/v2/reset_password/public/reset.html.twig
- templates/v2/user/strong_password/_password_strength_widget.html.twig
- templates/v2/user/strong_password/_strong_password_row.html.twig
- templates/v2/user_creation/beneficiary/create_beneficiary_step.html.twig
- tests/v2/Controller/GdprController/UpdatePasswordTest.php
- tests/v2/Manager/UserManager/GeneratePasswordTest.php
[Ticket](https://trello.com/c/mpV9uYPE/6147-5-etqa-et-etqsa-jai-un-mot-de-passe-de-minimum-20-caract%C3%A8res)
> 📦 ETQA et ETQSA, j'ai un mot de passe de minimum 20 caractères 

- templates/home/sections/digital_cares_section.html.twig
[Ticket](https://trello.com/c/cgbr82qF/6125-3-etqvistiteur-du-site-internet-sur-la-page-de-laccompagnement-num%C3%A9rique-je-vois-un-bouton-pour-acc%C3%A9der-au-catalogue-des-formati)
> 📦 ETQVistiteur du site internet, sur la page de l'accompagnement numérique je vois un bouton pour accéder au catalogue des formations des pros

- templates/components/event_form.html.twig
- yarn.lock
[Ticket](https://trello.com/c/mNtNLFgQ/6348-5-suite-maj-symfony-3)
> Sf Upgrade -> 🐛 [Event] Fix bug when adding reminders
